In [1]:
#load libraries
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import re, os

In [3]:
#read data
raw_data = pd.read_csv("/Users/albk/Documents/Code/Real_Projects/basketball_league_webapp/data/Carleton|Laurentian|2022-11-13.csv")
#raw_data = pd.read_csv(r"/content/drive/MyDrive/Colab Notebooks/NovaTech/Projects/1. Basketball netrating project/CarletonLaurentian2022-11-13.csv")

In [4]:
df= raw_data.copy()

In [5]:
df['V-event'] = df['V-event'].astype(str)

In [6]:
df.head()

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN

In [7]:
#clean data
players_list = np.array(['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN','SERAPH,REGINALD JEAN','LATIFF,WAZIR','SHEPHARD,GRANT','RILEY,BEN', 'SMAHA,GABRAEL','OKADO,MARJOK','BAILEY,ELLIOT','MEYER,EVAN','KNIGHT,JACOB','DOLMAN,LUKA','KATCHUNGA,JORDAN'])
event_list = np.array(['made layup','missed layup','Assist','Turnover','defensive rebound','enters the game','goes to the bench','missed 3-pt. jump shot','Foul','Steal','made free throw','missed free throw','made jump shot','made 3-pt. jump shot','missed jump shot','offensive rebound'])

In [8]:
#continue cleaning data
# Sample DataFrame and list of strings
#data = {'text_column': ['This is a sample text.', 'Another text here.', 'Yet another sample text.']}
#df = pd.DataFrame(data)#

#string_list = ['sample', 'text', 'another']

# Create a new column for each string in the list and initialize it with False
for search_term in event_list:
    df[search_term] = False

# Iterate over the list of strings and set the corresponding column to True if found
for search_term in event_list:
    df[search_term] = df['V-event'].str.contains(search_term)

In [9]:
# Create a new column for each string in the list and initialize it with False
for players_name in players_list:
    df[players_name] = False

# Iterate over the list of strings and set the corresponding column to True if found
for players_name in players_list:
    df[players_name] = df['V-event'].str.contains(players_name)

In [10]:
df.head(n=100)

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,"LATIFF,WAZIR","SHEPHARD,GRANT","RILEY,BEN","SMAHA,GABRAEL","OKADO,MARJOK","BAILEY,ELLIOT","MEYER,EVAN","KNIGHT,JACOB","DOLMAN,LUKA","KATCHUNGA,JORDAN"
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,03:02,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,False,False
96,96,03:02,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
97,97,02:55,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
98,98,02:55,NaN,NaN,6 - 20,"DOLMAN,LUKA offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,True,False
99,99,02:46,NaN,NaN,6 - 23,"WARNHOLTZ,AIDEN made 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [39]:
#creating a data frame of the events happening in the
# df2 = pd.DataFrame(columns=[event_list])
# df2.insert(loc=0, column='Players',value='')
# df2.head()

Empty DataFrame
Columns: [(Players,), (made layup,), (missed layup,), (Assist,), (Turnover,), (defensive rebound,), (enters the game,), (goes to the bench,), (missed 3-pt. jump shot,), (Foul,), (Steal,), (made free throw,), (missed free throw,), (made jump shot,), (made 3-pt. jump shot,), (missed jump shot,), (offensive rebound,)]
Index: []

In [40]:
# df2 = df.loc[df['VREEKEN,CONNOR'] == True]  ### this is just to test the data
# df2.head(n=100)

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,"LATIFF,WAZIR","SHEPHARD,GRANT","RILEY,BEN","SMAHA,GABRAEL","OKADO,MARJOK","BAILEY,ELLIOT","MEYER,EVAN","KNIGHT,JACOB","DOLMAN,LUKA","KATCHUNGA,JORDAN"
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
20,20,07:43,NaN,NaN,2 - 4,"VREEKEN,CONNOR missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
35,35,06:08,NaN,NaN,4 - 9,"Steal by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
53,53,06:00,NaN,NaN,5 - 13,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
67,67,04:41,NaN,NaN,5 - 16,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
77,77,03:49,NaN,NaN,5 - 18,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
84,84,03:49,NaN,NaN,6 - 18,"VREEKEN,CONNOR missed jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
110,110,01:42,NaN,NaN,6 - 25,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
113,113,01:26,NaN,NaN,6 - 25,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
127,127,00:39,NaN,NaN,8 - 25,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
156,156,09:45,NaN,NaN,8 - 29,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
164,164,08:23,NaN,NaN,10 - 29,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
206,206,07:40,NaN,NaN,13 - 36,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
220,220,06:54,NaN,NaN,13 - 36,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
266,266,04:08,NaN,NaN,21 - 39,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336,336,09:54,NaN,NaN,31 - 44,"VREEKEN,CONNOR missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
344,344,09:02,NaN,NaN,33 - 47,"Foul by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
352,352,08:23,NaN,NaN,34 - 47,"VREEKEN,CONNOR missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,False,False
360,360,08:13,NaN,NaN,34 - 48,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
366,366,08:13,NaN,NaN,34 - 49,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
404,404,06:25,NaN,NaN,39 - 51,"VREEKEN,CONNOR offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
410,410,06:25,NaN,NaN,39 - 51,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
432,432,04:18,NaN,NaN,41 - 52,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
442,442,03:54,NaN,NaN,41 - 54,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
475,475,00:00,NaN,NaN,47 - 56,"Foul by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
480,480,00:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
482,482,00:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
490,490,10:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
512,512,08:43,NaN,NaN,56 - 62,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
534,534,07:39,NaN,NaN,57 - 66,"VREEKEN,CONNOR offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
535,535,07:39,NaN,NaN,57 - 66,"VREEKEN,CONNOR missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,False,False
541,541,07:32,NaN,NaN,60 - 66,"Turnover by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
557,557,04:51,NaN,NaN,61 - 70,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
574,574,03:36,NaN,NaN,63 - 73,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
590,590,02:44,NaN,NaN,64 - 75,"Steal by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
591,591,02:44,NaN,NaN,64 - 77,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
596,596,02:44,NaN,NaN,64 - 80,"VREEKEN,CONNOR made 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
df3 = pd.DataFrame(columns=[event_list])

df3.head()

Empty DataFrame
Columns: [(made layup,), (missed layup,), (Assist,), (Turnover,), (defensive rebound,), (enters the game,), (goes to the bench,), (missed 3-pt. jump shot,), (Foul,), (Steal,), (made free throw,), (missed free throw,), (made jump shot,), (made 3-pt. jump shot,), (missed jump shot,), (offensive rebound,)]
Index: []

In [12]:
###############################
############################### This is working
###############################
###############################
for i in players_list:
    df2 = df.loc[df[i] == True]
    for x in event_list:
        a = len(df2[df2[x] == True])
        df3.at[i, x] = a


###############################
###############################
###############################
###############################
df3.head(n=20)

,made layup,missed layup,Assist,Turnover,defensive rebound,enters the game,goes to the bench,missed 3-pt. jump shot,Foul,Steal,made free throw,missed free throw,made jump shot,made 3-pt. jump shot,missed jump shot,offensive rebound
"VREEKEN,CONNOR",4,2,0,1,5,6,9,2,2,2,0,0,0,1,1,2
"WARNHOLTZ,AIDEN",1,5,12,2,10,2,3,5,4,0,6,1,0,3,3,2
"SERAPH,REGINALD JEAN",0,0,1,1,0,4,8,1,2,0,0,0,0,0,1,0
"LATIFF,WAZIR",0,5,6,2,6,4,5,6,1,3,2,0,0,2,0,0
"SHEPHARD,GRANT",5,5,0,1,8,5,7,0,2,0,9,6,0,0,0,6
"RILEY,BEN",0,1,0,1,1,8,4,0,3,0,2,0,0,0,0,0
"SMAHA,GABRAEL",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
"OKADO,MARJOK",0,0,1,2,3,7,5,1,5,0,0,0,1,1,0,2
"BAILEY,ELLIOT",4,1,1,1,0,8,5,2,5,2,1,4,0,1,1,2
"MEYER,EVAN",0,1,0,0,1,4,2,0,0,0,0,0,0,0,0,0
"KNIGHT,JACOB",0,0,0,1,0,2,2,0,0,0,0,0,0,0,0,0
"DOLMAN,LUKA",0,0,1,1,0,1,1,0,0,1,0,0,0,0,0,1
"KATCHUNGA,JORDAN",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [13]:
#like last time, we create a profile with the times this time for each player then we can create a loop!
#LEts start with the first player

df2 = df.loc[df['VREEKEN,CONNOR'] == True]

#turns out we dont need to do this.
#thats all it takes to have the players with the events.

In [15]:
#spliting the scores
#home and away scores
df[['Home score', 'Visitor score']] = df['Score'].str.split(' - ', expand=True)

In [90]:
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN','SERAPH,REGINALD JEAN','LATIFF,WAZIR','SHEPHARD,GRANT']

In [91]:
print(players_list)

['VREEKEN,CONNOR' 'WARNHOLTZ,AIDEN' 'SERAPH,REGINALD JEAN' 'LATIFF,WAZIR'
 'SHEPHARD,GRANT' 'RILEY,BEN' 'SMAHA,GABRAEL' 'OKADO,MARJOK'
 'BAILEY,ELLIOT' 'MEYER,EVAN' 'KNIGHT,JACOB' 'DOLMAN,LUKA'
 'KATCHUNGA,JORDAN']

In [92]:
df1 = df.copy()

In [93]:
df

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,"RILEY,BEN","SMAHA,GABRAEL","OKADO,MARJOK","BAILEY,ELLIOT","MEYER,EVAN","KNIGHT,JACOB","DOLMAN,LUKA","KATCHUNGA,JORDAN",Home score,Visitor score
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,False,False,False,...,False,False,False,False,False,False,False,False,Quarter 1,None
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,0,2
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton,False,False,True,...,False,False,False,False,False,False,False,False,0,2
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,0,2
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,606,02:20,NaN,NaN,64 - 80,"WARNHOLTZ,AIDEN offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,64,80
607,607,02:15,NaN,NaN,64 - 80,"SHEPHARD,GRANT missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,64,80
608,608,02:15,Laurentian,"CUDNEY,ETHAN defensive rebound",64 - 80,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,64,80
609,609,02:04,Laurentian,"SUTTON,MATTHEW missed 3-pt. jump shot",64 - 80,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,64,80
610,610,02:04,NaN,NaN,64 - 80,"LATIFF,WAZIR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,64,80

In [94]:
#AmirReza
# Find the column indices of the first and second True values in each row
first_true_col = (df.to_numpy() == True).argmax(axis=1)
df.iloc[:, first_true_col] = False  # Set the first True value to False to find the second True value
second_true_col = (df.to_numpy() == True).argmax(axis=1)

# Print the column names with the two True values
result = df[['Time','Home score','Visitor score']].copy()
# result = df[['Home score']].copy()
# result = df[ ['Visitor score']].copy()
result['First_True_Column'] = df.columns[first_true_col]
result['Second_True_Column'] = df.columns[second_true_col]
print(result)

          Time Home score Visitor score  First_True_Column Second_True_Column
0    Quarter 1  Quarter 1          None         Unnamed: 0         Unnamed: 0
1        09:58          0             2         Unnamed: 0     VREEKEN,CONNOR
2        09:58          0             2             Assist    WARNHOLTZ,AIDEN
3        09:44          0             2         Unnamed: 0         Unnamed: 0
4        09:44          0             2         Unnamed: 0         Unnamed: 0
..         ...        ...           ...                ...                ...
606      02:20         64            80  offensive rebound    WARNHOLTZ,AIDEN
607      02:15         64            80       missed layup     SHEPHARD,GRANT
608      02:15         64            80         Unnamed: 0         Unnamed: 0
609      02:04         64            80         Unnamed: 0         Unnamed: 0
610      02:04         64            80  defensive rebound       LATIFF,WAZIR

[611 rows x 5 columns]

In [95]:
quarter_indices = result[result['Time'].str.contains('Quarter')].index

In [97]:
quarter_indices[3]+1

488

In [98]:
quarter1 = result.loc[quarter_indices[0]+1:quarter_indices[1], ]
quarter2 = result.loc[quarter_indices[1]+1:quarter_indices[2], ]
quarter3 = result.loc[quarter_indices[2]+1:quarter_indices[3], ]
quarter4 = result.loc[quarter_indices[3]+1:, ]

In [99]:
quarter1 = quarter1.loc[~(quarter1 == "Unnamed: 0").any(axis=1)]
quarter2 = quarter2.loc[~(quarter2 == "Unnamed: 0").any(axis=1)]
quarter3 = quarter3.loc[~(quarter3 == "Unnamed: 0").any(axis=1)]
quarter4 = quarter4.loc[~(quarter4 == "Unnamed: 0").any(axis=1)]

In [100]:
desired_values = ['enters the game', 'goes to the bench']
filtered_rows1 = quarter1[quarter1['First_True_Column'].isin(desired_values)].reset_index(drop=True)
filtered_rows2 = quarter2[quarter2['First_True_Column'].isin(desired_values)].reset_index(drop=True)
filtered_rows3 = quarter3[quarter3['First_True_Column'].isin(desired_values)].reset_index(drop=True)
filtered_rows4 = quarter4[quarter4['First_True_Column'].isin(desired_values)].reset_index(drop=True)

In [101]:
print(filtered_rows1)

     Time Home score Visitor score  First_True_Column    Second_True_Column
0   08:45          0             4    enters the game             RILEY,BEN
1   08:45          0             4  goes to the bench  SERAPH,REGINALD JEAN
2   08:45          0             4  goes to the bench        SHEPHARD,GRANT
3   07:22          2             4    enters the game          OKADO,MARJOK
4   07:22          2             4  goes to the bench          LATIFF,WAZIR
5   06:00          5            13    enters the game            MEYER,EVAN
6   06:00          5            13    enters the game  SERAPH,REGINALD JEAN
7   06:00          5            13    enters the game          LATIFF,WAZIR
8   06:00          5            13    enters the game         BAILEY,ELLIOT
9   06:00          5            13  goes to the bench        VREEKEN,CONNOR
10  06:00          5            13  goes to the bench       WARNHOLTZ,AIDEN
11  06:00          5            13  goes to the bench             RILEY,BEN
12  04:41          5            16    enters the game        VREEKEN,CONNOR
13  04:41          5            16    enters the game        SHEPHARD,GRANT
14  04:41          5            16    enters the game          KNIGHT,JACOB
15  04:41          5            16  goes to the bench         BAILEY,ELLIOT
16  04:41          5            16  goes to the bench            MEYER,EVAN
17  04:41          5            16  goes to the bench          OKADO,MARJOK
18  03:23          6            20    enters the game       WARNHOLTZ,AIDEN
19  03:23          6            20  goes to the bench  SERAPH,REGINALD JEAN
20  03:23          6            20  goes to the bench        SHEPHARD,GRANT
21  02:08          6            23    enters the game           DOLMAN,LUKA
22  02:08          6            23  goes to the bench          KNIGHT,JACOB
23  00:39          8            25    enters the game         BAILEY,ELLIOT
24  00:39          8            25    enters the game             RILEY,BEN
25  00:39          8            25    enters the game            MEYER,EVAN
26  00:39          8            25    enters the game          OKADO,MARJOK
27  00:39          8            25  goes to the bench        VREEKEN,CONNOR
28  00:39          8            25  goes to the bench           DOLMAN,LUKA
29  00:39          8            25  goes to the bench          LATIFF,WAZIR

In [102]:
filtered_rows1[['Minutes', 'seconds']] = filtered_rows1['Time'].str.split(':', expand=True)

In [103]:
filtered_rows1['Minutes'] = pd.to_numeric(filtered_rows1['Minutes'])
filtered_rows1['seconds'] = pd.to_numeric(filtered_rows1['seconds'])

In [113]:
filtered_rows1['Time_sec'] = (filtered_rows1['Minutes']*60)+filtered_rows1['seconds']

In [114]:
filtered_rows1

,Time,Home score,Visitor score,First_True_Column,Second_True_Column,Minutes,seconds,Time_sec
0,08:45,0,4,enters the game,"RILEY,BEN",8,45,525
1,08:45,0,4,goes to the bench,"SERAPH,REGINALD JEAN",8,45,525
2,08:45,0,4,goes to the bench,"SHEPHARD,GRANT",8,45,525
3,07:22,2,4,enters the game,"OKADO,MARJOK",7,22,442
4,07:22,2,4,goes to the bench,"LATIFF,WAZIR",7,22,442
5,06:00,5,13,enters the game,"MEYER,EVAN",6,0,360
6,06:00,5,13,enters the game,"SERAPH,REGINALD JEAN",6,0,360
7,06:00,5,13,enters the game,"LATIFF,WAZIR",6,0,360
8,06:00,5,13,enters the game,"BAILEY,ELLIOT",6,0,360
9,06:00,5,13,goes to the bench,"VREEKEN,CONNOR",6,0,360
10,06:00,5,13,goes to the bench,"WARNHOLTZ,AIDEN",6,0,360
11,06:00,5,13,goes to the bench,"RILEY,BEN",6,0,360
12,04:41,5,16,enters the game,"VREEKEN,CONNOR",4,41,281
13,04:41,5,16,enters the game,"SHEPHARD,GRANT",4,41,281
14,04:41,5,16,enters the game,"KNIGHT,JACOB",4,41,281
15,04:41,5,16,goes to the bench,"BAILEY,ELLIOT",4,41,281
16,04:41,5,16,goes to the bench,"MEYER,EVAN",4,41,281
17,04:41,5,16,goes to the bench,"OKADO,MARJOK",4,41,281
18,03:23,6,20,enters the game,"WARNHOLTZ,AIDEN",3,23,203
19,03:23,6,20,goes to the bench,"SERAPH,REGINALD JEAN",3,23,203
20,03:23,6,20,goes to the bench,"SHEPHARD,GRANT",3,23,203
21,02:08,6,23,enters the game,"DOLMAN,LUKA",2,8,128
22,02:08,6,23,goes to the bench,"KNIGHT,JACOB",2,8,128
23,00:39,8,25,enters the game,"BAILEY,ELLIOT",0,39,39
24,00:39,8,25,enters the game,"RILEY,BEN",0,39,39
25,00:39,8,25,enters the game,"MEYER,EVAN",0,39,39
26,00:39,8,25,enters the game,"OKADO,MARJOK",0,39,39
27,00:39,8,25,goes to the bench,"VREEKEN,CONNOR",0,39,39
28,00:39,8,25,goes to the bench,"DOLMAN,LUKA",0,39,39
29,00:39,8,25,goes to the bench,"LATIFF,WAZIR",0,39,39

In [115]:
df22 = df1.copy()

In [116]:
# Extracting all unique players from the substitution columns
unique_players = pd.unique(filtered_rows1[['Second_True_Column']].values.ravel('K'))

# Initializing court times for all players
player_court_times_all = {player: 0 for player in unique_players if isinstance(player, str)}

# Reinitializing on-court status for all players (starting with everyone off-court)
on_court_all = {player: False for player in unique_players if isinstance(player, str)}

# Resetting last timestamp for the start of the quarter
last_timestamp_q1 = filtered_rows1['Time_sec'].iloc[-1]

# Iterate through each substitution event for all players
for index, row in filtered_rows1.iterrows():
    current_time_stamp = row['Time_sec']
    player = row['Second_True_Column']

    if player in on_court_all:
        # Update court time for players who are currently on the court
        for p in on_court_all:
            if on_court_all[p]:
                player_court_times_all[p] += last_timestamp_q1 - current_time_stamp

        # Update on-court status
        if row['First_True_Column'] == 'enters the game':
            on_court_all[player] = True
        elif row['First_True_Column'] == 'goes to the bench':
            on_court_all[player] = False

    # Update the last timestamp
    last_timestamp_q1 = current_time_stamp

# Add remaining time for players who were on the court at the end of the quarter
for p in on_court_all:
    if on_court_all[p]:
        player_court_times_all[p] += last_timestamp_q1

# Convert court times from seconds to minutes for all players
player_court_times_all_minutes = {player: time / 60 for player, time in player_court_times_all.items()}
player_court_times_all_minutes

{'RILEY,BEN': 3.4,
 'SERAPH,REGINALD JEAN': 2.6166666666666667,
 'SHEPHARD,GRANT': 1.3,
 'OKADO,MARJOK': 3.3333333333333335,
 'LATIFF,WAZIR': 5.35,
 'MEYER,EVAN': 1.9666666666666666,
 'BAILEY,ELLIOT': 1.9666666666666666,
 'VREEKEN,CONNOR': 4.033333333333333,
 'WARNHOLTZ,AIDEN': 3.3833333333333333,
 'KNIGHT,JACOB': 2.55,
 'DOLMAN,LUKA': 1.4833333333333334}

In [117]:
columns = ['lineup', 'PtScored', 'ptsconceded', 'off possession', 'def possession', 'minutes', 'home/away', 'opponent', 'date', 'game_type']

# Create an empty DataFrame with the specified columns
final_table = pd.DataFrame(columns=columns)

# Print the empty DataFrame
print(final_table)

Empty DataFrame
Columns: [lineup, PtScored, ptsconceded, off possession, def possession, minutes, home/away, opponent, date, game_type]
Index: []

In [ ]:
columns = ['Player Name', 'PtScored', 'ptsconceded', 'off possession', 'def possession', 'minutes', 'home/away', 'opponent', 'date', 'game_type']

# Create an empty DataFrame with the specified columns
final_table = pd.DataFrame(columns=columns)

# Print the empty DataFrame
print(final_table)

In [118]:
def calculate_player_points(data, scoring_values):
    """
    Calculate the total points scored by each player in a basketball game.

    Parameters:
    data (pd.DataFrame): DataFrame containing detailed play-by-play data.
    scoring_values (dict): Dictionary mapping scoring actions to their point values.

    Returns:
    dict: Total points scored by each player.
    """
    # Extracting player columns
    player_columns = data.columns[8:-2]

    # Initialize a dictionary to store the total points scored by each player
    player_points = {player: 0 for player in player_columns}

    # Function to calculate points based on scoring actions with the provided values
    def calculate_points(row):
        points = 0
        for action, value in scoring_values.items():
            if row[action]:
                points += value
        return points

    # Calculate points for each event in the game
    data['Points Scored'] = data.apply(calculate_points, axis=1)

    # Update points for each player
    for index, row in data.iterrows():
        for player in player_columns:
            if row[player]:
                player_points[player] += row['Points Scored']

    # Filter out players who didn't score any points
    player_points = {player: points for player, points in player_points.items() if points > 0}
    return player_points

In [119]:
scoring_values = {'made layup': 2, 'made free throw': 1, 'made jump shot': 2, 'made 3-pt. jump shot': 3}
calculate_player_points(df1.loc[quarter_indices[0]+1:quarter_indices[1], ], scoring_values)

C:\Users\amin8\AppData\Local\Temp\ipykernel_23852\2934469298.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Points Scored'] = data.apply(calculate_points, axis=1)

{'made free throw': 5,
 'made jump shot': 2,
 'made 3-pt. jump shot': 12,
 'VREEKEN,CONNOR': 6,
 'WARNHOLTZ,AIDEN': 11,
 'LATIFF,WAZIR': 3,
 'SHEPHARD,GRANT': 2,
 'OKADO,MARJOK': 5}

In [120]:
# Function to calculate points conceded by each player while on the court

def calculate_player_points_conceded_home(data, player_court_times):
    """
    Calculate the total points conceded by each player while they were on the court based on 'Home score'.

    Parameters:
    data (pd.DataFrame): DataFrame containing detailed play-by-play data.
    player_court_times (dict): Dictionary with players and their time on the court in minutes.

    Returns:
    dict: Total points conceded by each player while on the court.
    """
    # Initialize a dictionary to store points conceded while each player was on the court
    player_points_conceded = {player: 0 for player in player_court_times.keys()}

    # Calculate the difference in 'Home score' to determine points conceded in each event
    data['Points Conceded'] = data['Home score'].diff().fillna(0)

    # Iterate through the dataset and update points conceded for each player based on their court time
    for index, row in data.iterrows():
        for player in player_court_times.keys():
            if player_court_times.get(player, 0) > 0:  # Ensuring player is in the dictionary
                # Conceded points are counted for the visitor team's actions against the home team
                if 'Visitor' in row and row['Visitor'] and player in data.columns[28:]:  # Assuming Visitor players are in these columns
                    player_points_conceded[player] += row['Points Conceded']

    # Filter out players who didn't concede any points
    player_points_conceded = {player: points for player, points in player_points_conceded.items() if points > 0}
    return player_points_conceded

# Calculate points conceded for each player

In [121]:
data_detailed = df1.loc[quarter_indices[0]+1:quarter_indices[1], ]
data_detailed['Home score'] = pd.to_numeric(data_detailed['Home score'], errors='coerce')
# Calculating the total court time in seconds for each player from the data_q1 dataset
player_court_times_q1 = filtered_rows1.groupby('Second_True_Column')['Time_sec'].sum().to_dict()

# Convert the court times from seconds to minutes
player_court_times_q1 = {player: time / 60 for player, time in player_court_times_q1.items()}
points_conceded_home = calculate_player_points_conceded_home(data_detailed, player_court_times_q1)
points_conceded_home

C:\Users\amin8\AppData\Local\Temp\ipykernel_23852\1524318861.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_detailed['Home score'] = pd.to_numeric(data_detailed['Home score'], errors='coerce')
C:\Users\amin8\AppData\Local\Temp\ipykernel_23852\1860538089.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Points Conceded'] = data['Home score'].diff().fillna(0)

{'BAILEY,ELLIOT': 8.0,
 'DOLMAN,LUKA': 8.0,
 'KNIGHT,JACOB': 8.0,
 'MEYER,EVAN': 8.0,
 'OKADO,MARJOK': 8.0,
 'RILEY,BEN': 8.0}