In [2]:
#load libraries
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import re

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# #read data : armansamimi18@gmail.com
# raw_data = pd.read_csv(r"/content/drive/MyDrive/Amin-Arman/Copy of CarletonLaurentian2022-11-13.csv")
# #copy data
# raw_data2 = pd.read_csv(r"/content/drive/MyDrive/Amin-Arman/Copy of CarletonLaurentian2022-11-13.csv")

#read data : arman.samimi.ai.e@gmail.com
raw_data = pd.read_csv(r"/content/drive/MyDrive/datasets/CarletonLaurentian2022-11-13.csv")
#copy data
raw_data2 = pd.read_csv(r"/content/drive/MyDrive/datasets/CarletonLaurentian2022-11-13.csv")

In [6]:
df= raw_data.copy()

In [7]:
#  convert the data type to string
df['V-event'] = df['V-event'].astype(str)

In [8]:
dimensions = df.shape

# Access the number of rows and columns
num_rows = dimensions[0]
num_cols = dimensions[1]

# Print the dimensions
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)


df

Number of rows: 611
Number of columns: 7

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN
...,...,...,...,...,...,...,...
606,606,02:20,NaN,NaN,64 - 80,"WARNHOLTZ,AIDEN offensive rebound",Carleton
607,607,02:15,NaN,NaN,64 - 80,"SHEPHARD,GRANT missed layup",Carleton
608,608,02:15,Laurentian,"CUDNEY,ETHAN defensive rebound",64 - 80,nan,NaN
609,609,02:04,Laurentian,"SUTTON,MATTHEW missed 3-pt. jump shot",64 - 80,nan,NaN
610,610,02:04,NaN,NaN,64 - 80,"LATIFF,WAZIR defensive rebound",Carleton

In [7]:
df.head()

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN

In [9]:
#clean data
players_list = np.array(['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN','SERAPH,REGINALD JEAN','LATIFF,WAZIR','SHEPHARD,GRANT','RILEY,BEN', 'SMAHA,GABRAEL','OKADO,MARJOK','BAILEY,ELLIOT','MEYER,EVAN','KNIGHT,JACOB','DOLMAN,LUKA','KATCHUNGA,JORDAN'])
event_list = np.array(['made layup','missed layup','Assist','Turnover','defensive rebound','enters the game','goes to the bench','missed 3-pt. jump shot','Foul','Steal','made free throw','missed free throw','made jump shot','made 3-pt. jump shot','missed jump shot','offensive rebound'])
subsituation_list = np.array(['enters the game','goes to the bench'])
# attack_pos = np.array(['made layup','missed layup','Assist','missed 3-pt. jump shot'])
# defence_pos = np.array(['defensive rebound','missed jump shot','offensive rebound'])

In [ ]:
df.head()

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN

In [11]:
#continue cleaning data
# Sample DataFrame and list of strings
#data = {'text_column': ['This is a sample text.', 'Another text here.', 'Yet another sample text.']}
#df = pd.DataFrame(data)#

#string_list = ['sample', 'text', 'another']

# Create a new column for each string in the list and initialize it with False
for search_term in event_list:
    df[search_term] = False

# Iterate over the list of strings and set the corresponding column to True if found
for search_term in event_list:
    df[search_term] = df['V-event'].str.contains(search_term)



# for att_pos in attack_pos:
#     df[att_pos] = False

# for attack_pos in attack_pos:
#     df[att_pos] = df['V-event'].str.contains(att_pos)


# for att_pos in defence_pos:
#     df[att_pos] = False

# for attack_pos in defence_pos:
#     df[att_pos] = df['V-event'].str.contains(att_pos)

In [12]:
print(df[search_term])

0      False
1      False
2      False
3      False
4      False
       ...
606     True
607    False
608    False
609    False
610    False
Name: offensive rebound, Length: 611, dtype: bool

In [ ]:
df.head()

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,goes to the bench,missed 3-pt. jump shot,Foul,Steal,made free throw,missed free throw,made jump shot,made 3-pt. jump shot,missed jump shot,offensive rebound
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# Create a new column for each string in the list and initialize it with False
for players_name in players_list:
    df[players_name] = False

# Iterate over the list of strings and set the corresponding column to True if found
for players_name in players_list:
    df[players_name] = df['V-event'].str.contains(players_name)

In [ ]:
df.head(n=100)

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,"LATIFF,WAZIR","SHEPHARD,GRANT","RILEY,BEN","SMAHA,GABRAEL","OKADO,MARJOK","BAILEY,ELLIOT","MEYER,EVAN","KNIGHT,JACOB","DOLMAN,LUKA","KATCHUNGA,JORDAN"
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,03:02,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,False,False
96,96,03:02,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
97,97,02:55,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
98,98,02:55,NaN,NaN,6 - 20,"DOLMAN,LUKA offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,True,False
99,99,02:46,NaN,NaN,6 - 23,"WARNHOLTZ,AIDEN made 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
df["Unnamed: 0"]

0        0
1        1
2        2
3        3
4        4
      ...
606    606
607    607
608    608
609    609
610    610
Name: Unnamed: 0, Length: 611, dtype: int64

In [ ]:
# df['V-event'] = df['V-event'].astype(str)

In [14]:
# -------- Create a guide table to loooking for actions and subsitutation time ------------------------------

#Remove extra rows
df_filtered = df[~df['Time'].str.contains('Quarter')].copy()

# Create the 'guide_table' DataFrame with filtered data
guide_table = df_filtered[['Time', 'V-event']].copy()


# guide_table['lineup'] = guide_table.apply(lambda _: set(), axis=1)
# guide_table['lineup_list'] = guide_table.apply(lambda _: list(), axis=1)

first_lineup = ["VREEKEN,CONNOR", "WARNHOLTZ,AIDEN" , "SERAPH,REGINALD JEAN" , "LATIFF,WAZIR" ,"SHEPHARD,GRANT"]

# guide_table['lineup'] = guide_table.apply(lambda _: first_lineup, axis=1)
# guide_table['lineup_list'] = guide_table.apply(lambda _: first_lineup, axis=1)
# guide_table['lineup_list'] = guide_table['lineup_list'].astype(str)

# guide_table.loc[1, 'lineup_list'] = pd.Series(first_lineup)

# print(type(guide_table.loc[1, 'lineup_list']))
guide_table

      Time                            V-event
1    09:58          VREEKEN,CONNOR made layup
2    09:58          Assist by WARNHOLTZ,AIDEN
3    09:44                                nan
4    09:44                                nan
5    09:13   Turnover by SERAPH,REGINALD JEAN
..     ...                                ...
606  02:20  WARNHOLTZ,AIDEN offensive rebound
607  02:15        SHEPHARD,GRANT missed layup
608  02:15                                nan
609  02:04                                nan
610  02:04     LATIFF,WAZIR defensive rebound

[607 rows x 2 columns]

In [23]:




# --------------------- Print the dimensions of guide_table ------------------------------
dimensions = guide_table.shape
num_rows = dimensions[0]
num_cols = dimensions[1]
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)


# ----------- Create lineup array : each lineup is a set of players-----------------------
Lineup_table = [set() for _ in range(num_rows)]
# print(type(Lineup_table))
print(type(Lineup_table[0]))
# lineup
first_lineup =set(["VREEKEN,CONNOR", "WARNHOLTZ,AIDEN" , "SERAPH,REGINALD JEAN" , "LATIFF,WAZIR" ,"SHEPHARD,GRANT"])

# second_lineup = ["AAA,BBB", "WARNHOLTZ,AIDEN" , "SERAPH,REGINALD JEAN" , "LATIFF,WAZIR" ,"SHEPHARD,GRANT"]
Lineup_table[0].update(first_lineup)
# Lineup_table[1].update(second_lineup)
# print(Lineup_table[0])
# # we need a loop over guide_table event , read event and then update the lineup array
print(type(Lineup_table))
print(type(Lineup_table[0]))
# print(type(Lineup_table))
print(Lineup_table)

Number of rows: 607
Number of columns: 2
<class 'set'>
<class 'list'>
<class 'set'>
[{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}, set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set()]

In [16]:
# how to update add or remove a player to a set
out_player = 'SERAPH,REGINALD JEAN'
in_player= "Arman"
temp_lineup = Lineup_table[0]
print(temp_lineup)

temp_lineup.remove(out_player)
temp_lineup.add(in_player)
Lineup_table[0] = temp_lineup
print(Lineup_table[0])
print(type(Lineup_table[0]))

{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'Arman', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
<class 'set'>

In [18]:
# we need a loop over guide_table event , read event and then update the lineup array
print(len(guide_table))

subsitute_rows = guide_table[guide_table['V-event'].str.contains('enters|goes')]
# print(subsitute_rows)
# len(subsitute_rows)

subsituation_table = pd.DataFrame(columns=['Time', 'Player Out', 'Player In'])


for index, row in subsitute_rows.iterrows():
    if 'goes' in row['V-event']:
      player = row['V-event'].split()[0]
      # print(row["Time"] , player , "goes out")
      subsituation_table.loc[index, "Time"] = row["Time"]
      # subsituation_table.loc[index, "Action"] = row['V-event']
      subsituation_table.loc[index, "Player Out"] = player

    elif 'enters' in row['V-event']:
      player = row['V-event'].split()[0]
      # print(row["Time"] , player , "enters in")
      subsituation_table.loc[index,"Time"] = row["Time"]
      # subsituation_table.loc[index,"Action"] = row['V-event']
      subsituation_table.loc[index,"Player In"] = player

print(subsituation_table)
print(type(subsituation_table))
# ----------------------------------------- Well up to now --------------------------
# we have to loop over guide _table , read the time, update the Lineup_table based on subsituation_table

607
      Time       Player Out       Player In
14   08:45              NaN       RILEY,BEN
15   08:45              NaN  SAMAHA,GABRAEL
16   08:45  SERAPH,REGINALD             NaN
17   08:45   SHEPHARD,GRANT             NaN
25   07:22              NaN    OKADO,MARJOK
..     ...              ...             ...
557  04:51   VREEKEN,CONNOR             NaN
574  03:36              NaN  VREEKEN,CONNOR
575  03:36        RILEY,BEN             NaN
601  02:44              NaN       RILEY,BEN
602  02:44    BAILEY,ELLIOT             NaN

[114 rows x 3 columns]
<class 'pandas.core.frame.DataFrame'>

In [37]:
first_lineup =set(["VREEKEN,CONNOR", "WARNHOLTZ,AIDEN" , "SERAPH,REGINALD JEAN" , "LATIFF,WAZIR" ,"SHEPHARD,GRANT"])
# first_lineup.remove("Arman")
Lineup_table[0].update(first_lineup)
Lineup_table[0]
print (type(Lineup_table[0]) , type(Lineup_table))

<class 'set'> <class 'list'>

In [32]:
# how to copy and clear a lineup
# Lineup_table[1] = Lineup_table[0].copy()
Lineup_table[1].clear()
# Lineup_table

In [42]:

Lineup_table = [set() for _ in range(num_rows)]
# print(type(Lineup_table))
print(type(Lineup_table[0]))
# lineup
first_lineup =set(["VREEKEN,CONNOR", "WARNHOLTZ,AIDEN" , "SERAPH,REGINALD JEAN" , "LATIFF,WAZIR" ,"SHEPHARD,GRANT"])

# second_lineup = ["AAA,BBB", "WARNHOLTZ,AIDEN" , "SERAPH,REGINALD JEAN" , "LATIFF,WAZIR" ,"SHEPHARD,GRANT"]
Lineup_table[0].update(first_lineup)

# Loop over the rows of the guide_table
for index, row in guide_table.iterrows():
    time = row['Time']
    v_event = row['V-event']
    index = 0
    print (" in ",time, " action:" , v_event)
    if 'goes' not in v_event and 'enters' not in v_event:
        # Duplicate the last set in Lineup_table and append it to modified_lineup_table
        # print (" Normal action in ",time, " action:" , v_event)

        # the lineup is not changed , copy the previous lineup
        if index != 0:
         Lineup_table[index+1] = Lineup_table[index].copy()
    else:

        if 'goes' in v_event:
          out_player = v_event.split()[0]
          Lineup_table[index+1].remove(out_player)
          print (out_player , " is removed from the Line-up")
        elif 'enters' in v_event:
          in_player = v_event.split()[0]
          Lineup_table[index+1].add(in_player)
          print (in_player , " is added to the Line-up")
        # Extract the player from V-event
        # print (" Subsituation in ",time, " action:" , v_event)
    print(Lineup_table[index])
print(Lineup_table)

<class 'set'>
 in  09:58  action: VREEKEN,CONNOR made layup
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:58  action: Assist by WARNHOLTZ,AIDEN
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:44  action: nan
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:44  action: nan
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:13  action: Turnover by SERAPH,REGINALD JEAN
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:13  action: nan
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:13  action: nan
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:13  action: LATIFF,WAZIR defensive rebound
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:13  action: WARNHOLTZ,AIDEN made layup
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:13  action: Assist by LATIFF,WAZIR
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:05  action: nan
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  09:05  action: WARNHOLTZ,AIDEN defensive rebound
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  08:48  action: Turnover by SHEPHARD,GRANT
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  08:45  action: RILEY,BEN enters the game
RILEY,BEN  is added to the Line-up
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  08:45  action: SAMAHA,GABRAEL enters the game
SAMAHA,GABRAEL  is added to the Line-up
{'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'SERAPH,REGINALD JEAN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR'}
 in  08:45  action: SERAPH,REGINALD JEAN goes to the bench

KeyError: ignored

In [36]:
print(Lineup_table)

[{'SHEPHARD,GRANT', 'RILEY,BEN', 'WARNHOLTZ,AIDEN', 'VREEKEN,CONNOR', 'LATIFF,WAZIR', 'SAMAHA,GABRAEL', 'SERAPH,REGINALD JEAN'}, {'RILEY,BEN', 'SAMAHA,GABRAEL'}, set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set(), set()]

In [ ]:
# temp_lineup = guide_table.loc[1, 'lineup_list']
lineup_set = set(temp_lineup)
# print("old_lineup: ", lineup_set)

lineup_set.discard("SHEPHARD,GRANT")
lineup_set.add("SAMAHA,GABRAEL")

# print("updated_lineup : ", lineup_set)
updated_lineup_list = list(lineup_set)
print("updated_lineup_list:", updated_lineup_list)
print(type(updated_lineup_list))

print(type(guide_table.loc[1, 'lineup_list']))
print(guide_table.loc[1, 'lineup_list'])
# guide_table.loc[1, 'lineup_list'] = []

KeyError: ignored

In [ ]:
# access to a specifi lineup
temp_lineup = guide_table.loc[1, 'lineup'].copy()


print("old_lineup: ", temp_lineup)
print(type(temp_lineup), len(temp_lineup))
temp_lineup.discard("SHEPHARD,GRANT")
temp_lineup.add("SAMAHA,GABRAEL")
updated_lineup = temp_lineup.copy()

print("updated_lineup : ", updated_lineup)
print(type(updated_lineup), len(updated_lineup))

updated_lineup_list = list(updated_lineup)

# guide_table.loc[1, 'lineup_list'] = updated_lineup_list
# guide_table

KeyError: ignored

In [ ]:
guide_table.loc[1, 'lineup_list'].append(updated_lineup_list)

In [ ]:
guide_table

,Time,V-event,lineup,lineup_list
1,09:58,"VREEKEN,CONNOR made layup","{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...","[[VREEKEN,CONNOR, SAMAHA,GABRAEL, LATIFF,WAZIR..."
2,09:58,"Assist by WARNHOLTZ,AIDEN","{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]
3,09:44,nan,"{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]
4,09:44,nan,"{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]
5,09:13,"Turnover by SERAPH,REGINALD JEAN","{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]
...,...,...,...,...
606,02:20,"WARNHOLTZ,AIDEN offensive rebound","{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]
607,02:15,"SHEPHARD,GRANT missed layup","{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]
608,02:15,nan,"{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]
609,02:04,nan,"{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]
610,02:04,"LATIFF,WAZIR defensive rebound","{LATIFF,WAZIR, SHEPHARD,GRANT, WARNHOLTZ,AIDEN...",[]

In [ ]:
# # creating a profile for each player.
# # Initialize an empty profile DataFrame with the same columns as the original DataFrame
# profile_df = pd.DataFrame(columns=df[players_name])
#
# # Iterate through each column in the original DataFrame
# for col in df[players_name]:
#     # Check if the current column is True for all other columns
#     profile_df[col] = df.all(axis=1)  # True if all other columns are True, False otherwise
#
#

In [ ]:
profile_df.head()

NameError: name 'profile_df' is not defined

In [ ]:
#creating a data frame of the events happening in the
df2 = pd.DataFrame(columns=[event_list])
df2.insert(loc=0, column='Players',value='')
df2.head()

Empty DataFrame
Columns: [(Players,), (made layup,), (missed layup,), (Assist,), (Turnover,), (defensive rebound,), (enters the game,), (goes to the bench,), (missed 3-pt. jump shot,), (Foul,), (Steal,), (made free throw,), (missed free throw,), (made jump shot,), (made 3-pt. jump shot,), (missed jump shot,), (offensive rebound,)]
Index: []

In [ ]:
# for column in df[players_list]: # For each columns of Player names
#     print(column)
#     for k in players_list :
#           a=[len(df[df[k] == True]),column
#     ]
#     df2.loc[len(df2), :] = a # Append line
#

In [ ]:
# for column in df.columns[players_list]: # For each columns of name pattern `Result_xx`
#     print(column)
#     a = [column,
#         len(df[df[column] == True]),
#        ] # Create line as list
#
#     df2.loc[len(df2), :] = a # Append line

In [ ]:
df2 = df.loc[df['VREEKEN,CONNOR'] == True]

In [ ]:
df2.head(n=100)

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,"SERAPH,REGINALD JEAN","LATIFF,WAZIRSHEPHARD,GRANT","RILEY,BEN","SMAHA,GABRAEL","OKADO,MARJOK","BAILEY,ELLIOT","MEYER,EVAN","KNIGHT,JACOB","DOLMAN,LUKA","KATCHUNGA,JORDAN"
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
20,20,07:43,NaN,NaN,2 - 4,"VREEKEN,CONNOR missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
35,35,06:08,NaN,NaN,4 - 9,"Steal by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
53,53,06:00,NaN,NaN,5 - 13,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
67,67,04:41,NaN,NaN,5 - 16,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
77,77,03:49,NaN,NaN,5 - 18,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
84,84,03:49,NaN,NaN,6 - 18,"VREEKEN,CONNOR missed jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
110,110,01:42,NaN,NaN,6 - 25,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
113,113,01:26,NaN,NaN,6 - 25,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
127,127,00:39,NaN,NaN,8 - 25,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
156,156,09:45,NaN,NaN,8 - 29,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
164,164,08:23,NaN,NaN,10 - 29,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
206,206,07:40,NaN,NaN,13 - 36,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
220,220,06:54,NaN,NaN,13 - 36,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
266,266,04:08,NaN,NaN,21 - 39,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
336,336,09:54,NaN,NaN,31 - 44,"VREEKEN,CONNOR missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
344,344,09:02,NaN,NaN,33 - 47,"Foul by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
352,352,08:23,NaN,NaN,34 - 47,"VREEKEN,CONNOR missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,False,False
360,360,08:13,NaN,NaN,34 - 48,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
366,366,08:13,NaN,NaN,34 - 49,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
404,404,06:25,NaN,NaN,39 - 51,"VREEKEN,CONNOR offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
410,410,06:25,NaN,NaN,39 - 51,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
432,432,04:18,NaN,NaN,41 - 52,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
442,442,03:54,NaN,NaN,41 - 54,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
475,475,00:00,NaN,NaN,47 - 56,"Foul by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
480,480,00:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
482,482,00:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
490,490,10:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
512,512,08:43,NaN,NaN,56 - 62,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
534,534,07:39,NaN,NaN,57 - 66,"VREEKEN,CONNOR offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
535,535,07:39,NaN,NaN,57 - 66,"VREEKEN,CONNOR missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,False,False
541,541,07:32,NaN,NaN,60 - 66,"Turnover by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
557,557,04:51,NaN,NaN,61 - 70,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
574,574,03:36,NaN,NaN,63 - 73,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
590,590,02:44,NaN,NaN,64 - 75,"Steal by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False
591,591,02:44,NaN,NaN,64 - 77,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,False,False
596,596,02:44,NaN,NaN,64 - 80,"VREEKEN,CONNOR made 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df3 = pd.DataFrame(columns=[event_list])

df3.head()

Empty DataFrame
Columns: [(made layup,), (missed layup,), (Assist,), (Turnover,), (defensive rebound,), (enters the game,), (goes to the bench,), (missed 3-pt. jump shot,), (Foul,), (Steal,), (made free throw,), (missed free throw,), (made jump shot,), (made 3-pt. jump shot,), (missed jump shot,), (offensive rebound,)]
Index: []

In [ ]:
#############################
############################## This is working
##############################
#############################
for i in players_list:
    df2 = df.loc[df[i] == True]
    for x in event_list:
        a = len(df2[df2[x] == True])
        df3.at[i, x] = a


###############################
################################
###############################
###############################

In [ ]:
# i = 'VREEKEN,CONNOR'
# for x in event_list:
#         a = len(df[df[x] == True])
#         df3.at[i, x] = a

In [ ]:
df3.head(n=20)

,made layup,missed layup,Assist,Turnover,defensive rebound,enters the game,goes to the bench,missed 3-pt. jump shot,Foul,Steal,made free throw,missed free throw,made jump shot,made 3-pt. jump shot,missed jump shot,offensive rebound
"VREEKEN,CONNOR",4,2,0,1,5,6,9,2,2,2,0,0,0,1,1,2
"WARNHOLTZ,AIDEN",1,5,12,2,10,2,3,5,4,0,6,1,0,3,3,2
"SERAPH,REGINALD JEAN",0,0,1,1,0,4,8,1,2,0,0,0,0,0,1,0
"LATIFF,WAZIR",0,5,6,2,6,4,5,6,1,3,2,0,0,2,0,0
"SHEPHARD,GRANT",5,5,0,1,8,5,7,0,2,0,9,6,0,0,0,6
"RILEY,BEN",0,1,0,1,1,8,4,0,3,0,2,0,0,0,0,0
"SMAHA,GABRAEL",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
"OKADO,MARJOK",0,0,1,2,3,7,5,1,5,0,0,0,1,1,0,2
"BAILEY,ELLIOT",4,1,1,1,0,8,5,2,5,2,1,4,0,1,1,2
"MEYER,EVAN",0,1,0,0,1,4,2,0,0,0,0,0,0,0,0,0
"KNIGHT,JACOB",0,0,0,1,0,2,2,0,0,0,0,0,0,0,0,0
"DOLMAN,LUKA",0,0,1,1,0,1,1,0,0,1,0,0,0,0,0,1
"KATCHUNGA,JORDAN",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
# # Fill in a specific value in a specific cell
# row_index = 0  # Replace with the index of the row where you want to insert the value
# col_name = 'Players'  # Replace with the name of the column where you want to insert the value
# value_to_insert = 'VREEKEN,CONNOR'  # Replace with the value you want to insert
#
# # Using .at accessor
# df3.at[row_index, col_name] = value_to_insert

In [ ]:
# # Iterate through the column names (events) in df2
# my_list = []
# for i in event_list :
#     data_to_insert = len(df2[df2[i] == True])
#     my_list.append(data_to_insert)
#
# print(my_list)
# df3 = pd.DataFrame([my_list], columns=event_list)
# df3.head()

In [ ]:
# df4 = np.array(my_list)
# df4.head()

In [ ]:
# df3.loc[0,:]  = df4

In [ ]:
#like last time, we create a profile with the times this time for each player then we can create a loop!
#LEts start with the first player

df2 = df.loc[df['VREEKEN,CONNOR'] == True]

#turns out we dont need to do this.
#thats all it takes to have the players with the events.

In [ ]:
#spliting the scores
#home and away scores
df[['Home score', 'Visitor score']] = df['Score'].str.split(' - ', expand=True)

In [ ]:
df.head(n=500)

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,"RILEY,BEN","SMAHA,GABRAEL","OKADO,MARJOK","BAILEY,ELLIOT","MEYER,EVAN","KNIGHT,JACOB","DOLMAN,LUKA","KATCHUNGA,JORDAN",Home score,Visitor score
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,False,False,False,...,False,False,False,False,False,False,False,False,Quarter 1,None
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,0,2
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton,False,False,True,...,False,False,False,False,False,False,False,False,0,2
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,0,2
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,10:00,Laurentian,"LACROIX,CAILLOU goes to the bench",48 - 56,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,48,56
496,496,09:57,Laurentian,"CUDNEY,ETHAN made jump shot",50 - 56,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,50,56
497,497,09:57,Laurentian,"Assist by KATCHUNGA,JORDAN",50 - 56,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,50,56
498,498,09:37,NaN,NaN,50 - 59,"LATIFF,WAZIR made 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,50,59
499,499,09:37,NaN,NaN,50 - 59,"Assist by WARNHOLTZ,AIDEN",Carleton,False,False,True,...,False,False,False,False,False,False,False,False,50,59

In [ ]:
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN','SERAPH,REGINALD JEAN','LATIFF,WAZIR','SHEPHARD,GRANT']

In [ ]:
df2 = df.loc[df['VREEKEN,CONNOR'] == True]

In [ ]:
df2.head(n=100)

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,"RILEY,BEN","SMAHA,GABRAEL","OKADO,MARJOK","BAILEY,ELLIOT","MEYER,EVAN","KNIGHT,JACOB","DOLMAN,LUKA","KATCHUNGA,JORDAN",Home score,Visitor score
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,0,2
20,20,07:43,NaN,NaN,2 - 4,"VREEKEN,CONNOR missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,2,4
35,35,06:08,NaN,NaN,4 - 9,"Steal by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,4,9
53,53,06:00,NaN,NaN,5 - 13,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,5,13
67,67,04:41,NaN,NaN,5 - 16,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,5,16
77,77,03:49,NaN,NaN,5 - 18,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,5,18
84,84,03:49,NaN,NaN,6 - 18,"VREEKEN,CONNOR missed jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,6,18
110,110,01:42,NaN,NaN,6 - 25,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,6,25
113,113,01:26,NaN,NaN,6 - 25,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,6,25
127,127,00:39,NaN,NaN,8 - 25,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,8,25
156,156,09:45,NaN,NaN,8 - 29,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,8,29
164,164,08:23,NaN,NaN,10 - 29,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,10,29
206,206,07:40,NaN,NaN,13 - 36,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,13,36
220,220,06:54,NaN,NaN,13 - 36,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,13,36
266,266,04:08,NaN,NaN,21 - 39,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,21,39
336,336,09:54,NaN,NaN,31 - 44,"VREEKEN,CONNOR missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,31,44
344,344,09:02,NaN,NaN,33 - 47,"Foul by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,33,47
352,352,08:23,NaN,NaN,34 - 47,"VREEKEN,CONNOR missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,34,47
360,360,08:13,NaN,NaN,34 - 48,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,34,48
366,366,08:13,NaN,NaN,34 - 49,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,34,49
404,404,06:25,NaN,NaN,39 - 51,"VREEKEN,CONNOR offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,39,51
410,410,06:25,NaN,NaN,39 - 51,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,39,51
432,432,04:18,NaN,NaN,41 - 52,"VREEKEN,CONNOR defensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,41,52
442,442,03:54,NaN,NaN,41 - 54,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,41,54
475,475,00:00,NaN,NaN,47 - 56,"Foul by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,47,56
480,480,00:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,48,56
482,482,00:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,48,56
490,490,10:00,NaN,NaN,48 - 56,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,48,56
512,512,08:43,NaN,NaN,56 - 62,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,56,62
534,534,07:39,NaN,NaN,57 - 66,"VREEKEN,CONNOR offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,57,66
535,535,07:39,NaN,NaN,57 - 66,"VREEKEN,CONNOR missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,57,66
541,541,07:32,NaN,NaN,60 - 66,"Turnover by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,60,66
557,557,04:51,NaN,NaN,61 - 70,"VREEKEN,CONNOR goes to the bench",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,61,70
574,574,03:36,NaN,NaN,63 - 73,"VREEKEN,CONNOR enters the game",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,63,73
590,590,02:44,NaN,NaN,64 - 75,"Steal by VREEKEN,CONNOR",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,64,75
591,591,02:44,NaN,NaN,64 - 77,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,64,77
596,596,02:44,NaN,NaN,64 - 80,"VREEKEN,CONNOR made 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,64,80

In [ ]:
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN','SERAPH,REGINALD JEAN','LATIFF,WAZIR','SHEPHARD,GRANT']

In [ ]:
print(players_list)

['VREEKEN,CONNOR' 'WARNHOLTZ,AIDEN' 'SERAPH,REGINALD JEAN'
 'LATIFF,WAZIRSHEPHARD,GRANT' 'RILEY,BEN' 'SMAHA,GABRAEL' 'OKADO,MARJOK'
 'BAILEY,ELLIOT' 'MEYER,EVAN' 'KNIGHT,JACOB' 'DOLMAN,LUKA'
 'KATCHUNGA,JORDAN']

In [ ]:
df.head(n=100)

,Unnamed: 0,Time,Home,H-event,Score,V-event,Visitor,made layup,missed layup,Assist,...,"RILEY,BEN","SMAHA,GABRAEL","OKADO,MARJOK","BAILEY,ELLIOT","MEYER,EVAN","KNIGHT,JACOB","DOLMAN,LUKA","KATCHUNGA,JORDAN",Home score,Visitor score
0,0,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,Quarter 1,False,False,False,...,False,False,False,False,False,False,False,False,Quarter 1,None
1,1,09:58,NaN,NaN,0 - 2,"VREEKEN,CONNOR made layup",Carleton,True,False,False,...,False,False,False,False,False,False,False,False,0,2
2,2,09:58,NaN,NaN,0 - 2,"Assist by WARNHOLTZ,AIDEN",Carleton,False,False,True,...,False,False,False,False,False,False,False,False,0,2
3,3,09:44,Laurentian,"SCOTT,COBAN missed jump shot",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,0,2
4,4,09:44,Laurentian,"COULIBALY,SALIM offensive rebound",0 - 2,nan,NaN,False,False,False,...,False,False,False,False,False,False,False,False,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,03:02,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN missed layup",Carleton,False,True,False,...,False,False,False,False,False,False,False,False,6,20
96,96,03:02,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,6,20
97,97,02:55,NaN,NaN,6 - 20,"WARNHOLTZ,AIDEN missed 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,6,20
98,98,02:55,NaN,NaN,6 - 20,"DOLMAN,LUKA offensive rebound",Carleton,False,False,False,...,False,False,False,False,False,False,True,False,6,20
99,99,02:46,NaN,NaN,6 - 23,"WARNHOLTZ,AIDEN made 3-pt. jump shot",Carleton,False,False,False,...,False,False,False,False,False,False,False,False,6,23

In [ ]:
# Create a sample DataFrame with random True/False values
# np.random.seed(0)  # for reproducibility
# data = np.random.choice([True, False], size=(100, 37))
# df = pd.DataFrame(data, columns=[f'Var{i}' for i in range(1, 38)])
#
# # Find the column indices of the first and second True values in each row
# first_true_col = df.apply(lambda row: row.idxmax(), axis=1)
# df[first_true_col] = False  # Set the first True value to False to find the second True value
# second_true_col = df.apply(lambda row: row.idxmax(), axis=1)
#
# # Print the column names with the two True values

In [ ]:
# Find the column indices of the first and second True values in each row
first_true_col = (df.to_numpy() == True).argmax(axis=1)
df.iloc[:, first_true_col] = False  # Set the first True value to False to find the second True value
second_true_col = (df.to_numpy() == True).argmax(axis=1)

# Print the column names with the two True values
result = df[['Time','Home score','Visitor score']].copy()
# result = df[['Home score']].copy()
# result = df[ ['Visitor score']].copy()
result['First_True_Column'] = df.columns[first_true_col]
result['Second_True_Column'] = df.columns[second_true_col]
print(result)

          Time Home score Visitor score  First_True_Column Second_True_Column
0    Quarter 1  Quarter 1          None         Unnamed: 0         Unnamed: 0
1        09:58          0             2         Unnamed: 0     VREEKEN,CONNOR
2        09:58          0             2             Assist    WARNHOLTZ,AIDEN
3        09:44          0             2         Unnamed: 0         Unnamed: 0
4        09:44          0             2         Unnamed: 0         Unnamed: 0
..         ...        ...           ...                ...                ...
606      02:20         64            80  offensive rebound    WARNHOLTZ,AIDEN
607      02:15         64            80       missed layup     SHEPHARD,GRANT
608      02:15         64            80         Unnamed: 0         Unnamed: 0
609      02:04         64            80         Unnamed: 0         Unnamed: 0
610      02:04         64            80  defensive rebound       LATIFF,WAZIR

[611 rows x 5 columns]

In [ ]:
# result = result.loc[~(result == "Unnamed: 0").any(axis=1)]

In [ ]:
desired_values = ['enters the game', 'goes to the bench']
filtered_rows = result[result['First_True_Column'].isin(desired_values)]

In [ ]:
print(filtered_rows)

      Time Home score Visitor score  First_True_Column    Second_True_Column
14   08:45          0             4    enters the game             RILEY,BEN
15   08:45          0             4    enters the game            Unnamed: 0
16   08:45          0             4  goes to the bench  SERAPH,REGINALD JEAN
17   08:45          0             4  goes to the bench            Unnamed: 0
25   07:22          2             4    enters the game          OKADO,MARJOK
..     ...        ...           ...                ...                   ...
557  04:51         61            70  goes to the bench        VREEKEN,CONNOR
574  03:36         63            73    enters the game        VREEKEN,CONNOR
575  03:36         63            73  goes to the bench             RILEY,BEN
601  02:44         64            80    enters the game             RILEY,BEN
602  02:44         64            80  goes to the bench         BAILEY,ELLIOT

[114 rows x 5 columns]

In [ ]:
quarter_indices = result[result['Time'].str.contains('Quarter')].index

In [ ]:
quarter_indices[3]+1

488

In [ ]:
quarter1 = result.loc[quarter_indices[0]+1:quarter_indices[1], ]
quarter2 = result.loc[quarter_indices[1]+1:quarter_indices[2], ]
quarter3 = result.loc[quarter_indices[2]+1:quarter_indices[3], ]
quarter4 = result.loc[quarter_indices[3]+1:, ]

In [ ]:
quarter1 = quarter1.loc[~(quarter1 == "Unnamed: 0").any(axis=1)]
quarter2 = quarter2.loc[~(quarter2 == "Unnamed: 0").any(axis=1)]
quarter3 = quarter3.loc[~(quarter3 == "Unnamed: 0").any(axis=1)]
quarter4 = quarter4.loc[~(quarter4 == "Unnamed: 0").any(axis=1)]

In [ ]:
desired_values = ['enters the game', 'goes to the bench']
filtered_rows1 = quarter1[quarter1['First_True_Column'].isin(desired_values)].reset_index(drop=True)
filtered_rows2 = quarter2[quarter2['First_True_Column'].isin(desired_values)].reset_index(drop=True)
filtered_rows3 = quarter3[quarter3['First_True_Column'].isin(desired_values)].reset_index(drop=True)
filtered_rows4 = quarter4[quarter4['First_True_Column'].isin(desired_values)].reset_index(drop=True)

In [ ]:
filtered_rows1[['Minutes', 'seconds']] = filtered_rows1['Time'].str.split(':', expand=True)

In [ ]:
filtered_rows1['Minutes'] = pd.to_numeric(filtered_rows1['Minutes'])
filtered_rows1['seconds'] = pd.to_numeric(filtered_rows1['seconds'])

In [ ]:
filtered_rows1['Time_sec'] = (filtered_rows1['Minutes']*60)+filtered_rows1['seconds']

In [ ]:
filtered_rows1

,Time,Home score,Visitor score,First_True_Column,Second_True_Column,Minutes,seconds,Time_sec
0,08:45,0,4,enters the game,"RILEY,BEN",8,45,525
1,08:45,0,4,goes to the bench,"SERAPH,REGINALD JEAN",8,45,525
2,08:45,0,4,goes to the bench,"SHEPHARD,GRANT",8,45,525
3,07:22,2,4,enters the game,"OKADO,MARJOK",7,22,442
4,07:22,2,4,goes to the bench,"LATIFF,WAZIR",7,22,442
5,06:00,5,13,enters the game,"MEYER,EVAN",6,0,360
6,06:00,5,13,enters the game,"SERAPH,REGINALD JEAN",6,0,360
7,06:00,5,13,enters the game,"LATIFF,WAZIR",6,0,360
8,06:00,5,13,enters the game,"BAILEY,ELLIOT",6,0,360
9,06:00,5,13,goes to the bench,"VREEKEN,CONNOR",6,0,360
10,06:00,5,13,goes to the bench,"WARNHOLTZ,AIDEN",6,0,360
11,06:00,5,13,goes to the bench,"RILEY,BEN",6,0,360
12,04:41,5,16,enters the game,"VREEKEN,CONNOR",4,41,281
13,04:41,5,16,enters the game,"SHEPHARD,GRANT",4,41,281
14,04:41,5,16,enters the game,"KNIGHT,JACOB",4,41,281
15,04:41,5,16,goes to the bench,"BAILEY,ELLIOT",4,41,281
16,04:41,5,16,goes to the bench,"MEYER,EVAN",4,41,281
17,04:41,5,16,goes to the bench,"OKADO,MARJOK",4,41,281
18,03:23,6,20,enters the game,"WARNHOLTZ,AIDEN",3,23,203
19,03:23,6,20,goes to the bench,"SERAPH,REGINALD JEAN",3,23,203
20,03:23,6,20,goes to the bench,"SHEPHARD,GRANT",3,23,203
21,02:08,6,23,enters the game,"DOLMAN,LUKA",2,8,128
22,02:08,6,23,goes to the bench,"KNIGHT,JACOB",2,8,128
23,00:39,8,25,enters the game,"BAILEY,ELLIOT",0,39,39
24,00:39,8,25,enters the game,"RILEY,BEN",0,39,39
25,00:39,8,25,enters the game,"MEYER,EVAN",0,39,39
26,00:39,8,25,enters the game,"OKADO,MARJOK",0,39,39
27,00:39,8,25,goes to the bench,"VREEKEN,CONNOR",0,39,39
28,00:39,8,25,goes to the bench,"DOLMAN,LUKA",0,39,39
29,00:39,8,25,goes to the bench,"LATIFF,WAZIR",0,39,39

In [ ]:
filtered_rows1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                30 non-null     object
 1   Home score          30 non-null     object
 2   Visitor score       30 non-null     object
 3   First_True_Column   30 non-null     object
 4   Second_True_Column  30 non-null     object
 5   Minutes             30 non-null     int64
 6   seconds             30 non-null     int64
 7   Time_sec            30 non-null     int64
dtypes: int64(3), object(5)
memory usage: 2.0+ KB

In [ ]:
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN','SERAPH,REGINALD JEAN','LATIFF,WAZIR','SHEPHARD,GRANT']

In [ ]:
columns = ['lineup', 'PtScored', 'ptsconceded', 'off possession', 'def possession', 'minutes', 'home/away', 'opponent', 'date', 'game_type']

# Create an empty DataFrame with the specified columns
final_table = pd.DataFrame(columns=columns)

# Print the empty DataFrame
print(final_table)

Empty DataFrame
Columns: [lineup, PtScored, ptsconceded, off possession, def possession, minutes, home/away, opponent, date, game_type]
Index: []

In [ ]:
final_table.loc[0, 'lineup'] = ', '.join(starter)

In [ ]:
final_table

,lineup,PtScored,ptsconceded,off possession,def possession,minutes,home/away,opponent,date,game_type
0,"VREEKEN,CONNOR, WARNHOLTZ,AIDEN, SERAPH,REGINA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
first_pts = [filtered_rows1.loc[0, 'Visitor score']]
pts_conceded = [filtered_rows1.loc[0, 'Home score']]
#time = pd.to_str[600 - filtered_rows1.loc[0,'Time_sec']]
home_away = ['away'] ##need to figure this out how to read it from the data
opponent = ['lorentiean'] #need to read it from the data as well

In [ ]:
final_table.loc[0, 'ptsconceded'] = ', '.join(pts_conceded)
#final_table.loc[0, 'minutes'] = ', '.join(time)
final_table.loc[0, 'home/away'] = ', '.join(home_away)
final_table.loc[0, 'opponent'] = ', '.join(opponent)

In [ ]:
final_table.loc[1, 'lineup'] = ', '.join()

TypeError: join() takes exactly one argument (0 given)

In [ ]:
final_table.loc[0, 'lineup'] = ', '.join(starter)

In [ ]:
value_to_find = 'goes to the bench'
second_value = 'enters the game'
first_occurrence_index = (filtered_rows1['First_True_Column'] == value_to_find).idxmax()
second_occurrence_index = (filtered_rows1['First_True_Column'] == second_value).idxmax()

In [ ]:
# Define the value to find and the replacement
value_to_find = filtered_rows1.loc[first_occurrence_index,'Second_True_Column']
replacement_value = filtered_rows1.loc[second_occurrence_index,'Second_True_Column']  # Replace with 'Regi'

# Using a list comprehension to replace the value
starter_updated = [replacement_value if player == value_to_find else player for player in starter]

# Print the updated list
print(starter_updated)

['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'RILEY,BEN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

In [ ]:
df= pd.DataFrame(filtered_rows1)

# Assuming the data is in a DataFrame named df
df['Time_sec'] = df['Minutes']*60 + df['seconds']

# Calculate the points scored and conceded when each player is on the court
df['points_scored'] = pd.to_numeric(df['Visitor score']).diff().where(df['First_True_Column'] == 'enters the game')
df['points_conceded'] = pd.to_numeric(df['Home score']).diff().where(df['First_True_Column'] == 'enters the game')

# Calculate the time each player spent on the court
df['enter_time'] = df['Time_sec'].where(df['First_True_Column'] == 'enters the game')
df['leave_time'] = df['Time_sec'].where(df['First_True_Column'] == 'goes to the bench')
df['time_on_court'] = df.groupby('Second_True_Column')['leave_time'].shift() - df['enter_time']

# Group by player and calculate total points scored, conceded and total time on court
player_stats = df.groupby('Second_True_Column').agg({'points_scored': 'sum', 'points_conceded': 'sum', 'time_on_court': 'sum'})

# Calculate net rating for each player
player_stats['net_rating'] = (player_stats['points_scored'] - player_stats['points_conceded']) / player_stats['time_on_court']

# Calculate net rating for the lineup
lineup = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN','SERAPH,REGINALD JEAN','LATIFF,WAZIR','SHEPHARD,GRANT']

# Check if all players in lineup are in player_stats
if set(lineup).issubset(player_stats.index):
    lineup_stats = player_stats.loc[lineup].sum()
    lineup_net_rating = (lineup_stats['points_scored'] - lineup_stats['points_conceded']) / lineup_stats['time_on_court']
    print('Lineup Net Rating:', lineup_net_rating)
else:
    missing_players = set(lineup) - set(player_stats.index)
    print(f'The following players in your lineup are not present in Second_True_Column: {missing_players}')

print(player_stats)

Lineup Net Rating: 0.008253094910591471
                      points_scored  points_conceded  time_on_court  \
Second_True_Column
BAILEY,ELLIOT                   2.0              2.0          242.0
DOLMAN,LUKA                     3.0              0.0            0.0
KNIGHT,JACOB                    0.0              0.0            0.0
LATIFF,WAZIR                    0.0              0.0           82.0
MEYER,EVAN                      9.0              3.0          242.0
OKADO,MARJOK                    0.0              2.0          242.0
RILEY,BEN                       0.0              0.0          321.0
SERAPH,REGINALD JEAN            0.0              0.0          165.0
SHEPHARD,GRANT                  0.0              0.0          244.0
VREEKEN,CONNOR                  3.0              0.0           79.0
WARNHOLTZ,AIDEN                 4.0              1.0          157.0

                      net_rating
Second_True_Column
BAILEY,ELLIOT           0.000000
DOLMAN,LUKA                  inf
KNIGHT,JACOB                 NaN
LATIFF,WAZIR            0.000000
MEYER,EVAN              0.024793
OKADO,MARJOK           -0.008264
RILEY,BEN               0.000000
SERAPH,REGINALD JEAN    0.000000
SHEPHARD,GRANT          0.000000
VREEKEN,CONNOR          0.037975
WARNHOLTZ,AIDEN         0.019108

In [ ]:
player_stats

,points_scored,points_conceded,time_on_court,net_rating
Second_True_Column,,,,
"BAILEY,ELLIOT",2.0,2.0,242.0,0.000000
"DOLMAN,LUKA",3.0,0.0,0.0,inf
"KNIGHT,JACOB",0.0,0.0,0.0,NaN
"LATIFF,WAZIR",0.0,0.0,82.0,0.000000
"MEYER,EVAN",9.0,3.0,242.0,0.024793
"OKADO,MARJOK",0.0,2.0,242.0,-0.008264
"RILEY,BEN",0.0,0.0,321.0,0.000000
"SERAPH,REGINALD JEAN",0.0,0.0,165.0,0.000000
"SHEPHARD,GRANT",0.0,0.0,244.0,0.000000
"VREEKEN,CONNOR",3.0,0.0,79.0,0.037975
"WARNHOLTZ,AIDEN",4.0,1.0,157.0,0.019108

In [ ]:
filtered_rows1['Home score'] = pd.to_numeric(filtered_rows1['Home score'])
filtered_rows1['Visitor score'] = pd.to_numeric(filtered_rows1['Visitor score'])

In [ ]:
df = pd.DataFrame(filtered_rows1)

# Starting lineup
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = starting_lineup.copy()

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) < 5:
                    player_in = current_lineup[-1]
                    current_lineup.append(player_in)
                    player_substitutions.append((player, player_in))

    return player_substitutions

player_substitutions = track_player_substitutions(df, starter)
print(player_substitutions)

[('VREEKEN,CONNOR', 'RILEY,BEN'), ('SERAPH,REGINALD JEAN', 'RILEY,BEN'), ('SHEPHARD,GRANT', 'RILEY,BEN'), ('WARNHOLTZ,AIDEN', 'OKADO,MARJOK'), ('LATIFF,WAZIR', 'OKADO,MARJOK'), ('RILEY,BEN', 'MEYER,EVAN'), ('RILEY,BEN', 'SERAPH,REGINALD JEAN'), ('RILEY,BEN', 'LATIFF,WAZIR'), ('OKADO,MARJOK', 'BAILEY,ELLIOT'), ('OKADO,MARJOK', 'VREEKEN,CONNOR'), ('MEYER,EVAN', 'SHEPHARD,GRANT'), ('SERAPH,REGINALD JEAN', 'KNIGHT,JACOB'), ('BAILEY,ELLIOT', 'KNIGHT,JACOB'), ('LATIFF,WAZIR', 'WARNHOLTZ,AIDEN'), ('SHEPHARD,GRANT', 'WARNHOLTZ,AIDEN'), ('VREEKEN,CONNOR', 'DOLMAN,LUKA'), ('KNIGHT,JACOB', 'DOLMAN,LUKA'), ('KNIGHT,JACOB', 'BAILEY,ELLIOT'), ('WARNHOLTZ,AIDEN', 'RILEY,BEN'), ('WARNHOLTZ,AIDEN', 'MEYER,EVAN'), ('DOLMAN,LUKA', 'OKADO,MARJOK'), ('DOLMAN,LUKA', 'OKADO,MARJOK')]

In [ ]:
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = starting_lineup.copy()
    lineup_history = []

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) < 5:
                    player_in = current_lineup[-1]
                    current_lineup.append(player_in)
                    player_substitutions.append((player, player_in))

        lineup_history.append(current_lineup.copy())

    return player_substitutions, lineup_history

player_substitutions, lineup_history = track_player_substitutions(df, starter)
print(player_substitutions)
print(lineup_history)

[('VREEKEN,CONNOR', 'RILEY,BEN'), ('SERAPH,REGINALD JEAN', 'RILEY,BEN'), ('SHEPHARD,GRANT', 'RILEY,BEN'), ('WARNHOLTZ,AIDEN', 'OKADO,MARJOK'), ('LATIFF,WAZIR', 'OKADO,MARJOK'), ('RILEY,BEN', 'MEYER,EVAN'), ('RILEY,BEN', 'SERAPH,REGINALD JEAN'), ('RILEY,BEN', 'LATIFF,WAZIR'), ('OKADO,MARJOK', 'BAILEY,ELLIOT'), ('OKADO,MARJOK', 'VREEKEN,CONNOR'), ('MEYER,EVAN', 'SHEPHARD,GRANT'), ('SERAPH,REGINALD JEAN', 'KNIGHT,JACOB'), ('BAILEY,ELLIOT', 'KNIGHT,JACOB'), ('LATIFF,WAZIR', 'WARNHOLTZ,AIDEN'), ('SHEPHARD,GRANT', 'WARNHOLTZ,AIDEN'), ('VREEKEN,CONNOR', 'DOLMAN,LUKA'), ('KNIGHT,JACOB', 'DOLMAN,LUKA'), ('KNIGHT,JACOB', 'BAILEY,ELLIOT'), ('WARNHOLTZ,AIDEN', 'RILEY,BEN'), ('WARNHOLTZ,AIDEN', 'MEYER,EVAN'), ('DOLMAN,LUKA', 'OKADO,MARJOK'), ('DOLMAN,LUKA', 'OKADO,MARJOK')]
[['WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'RILEY,BEN'], ['WARNHOLTZ,AIDEN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT', 'RILEY,BEN', 'RILEY,BEN'], ['WARNHOLTZ,AIDEN', 'LATIFF,WAZIR', 'RILEY,BEN', 'RILEY,BEN', 'RILEY,BEN'], ['LATIFF,WAZIR', 'RILEY,BEN', 'RILEY,BEN', 'RILEY,BEN', 'OKADO,MARJOK'], ['RILEY,BEN', 'RILEY,BEN', 'RILEY,BEN', 'OKADO,MARJOK', 'OKADO,MARJOK'], ['RILEY,BEN', 'RILEY,BEN', 'OKADO,MARJOK', 'OKADO,MARJOK', 'MEYER,EVAN'], ['RILEY,BEN', 'OKADO,MARJOK', 'OKADO,MARJOK', 'MEYER,EVAN', 'SERAPH,REGINALD JEAN'], ['OKADO,MARJOK', 'OKADO,MARJOK', 'MEYER,EVAN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR'], ['OKADO,MARJOK', 'MEYER,EVAN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'BAILEY,ELLIOT'], ['OKADO,MARJOK', 'MEYER,EVAN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'BAILEY,ELLIOT'], ['OKADO,MARJOK', 'MEYER,EVAN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'BAILEY,ELLIOT'], ['OKADO,MARJOK', 'MEYER,EVAN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'BAILEY,ELLIOT'], ['MEYER,EVAN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'BAILEY,ELLIOT', 'VREEKEN,CONNOR'], ['SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'BAILEY,ELLIOT', 'VREEKEN,CONNOR', 'SHEPHARD,GRANT'], ['LATIFF,WAZIR', 'BAILEY,ELLIOT', 'VREEKEN,CONNOR', 'SHEPHARD,GRANT', 'KNIGHT,JACOB'], ['LATIFF,WAZIR', 'VREEKEN,CONNOR', 'SHEPHARD,GRANT', 'KNIGHT,JACOB', 'KNIGHT,JACOB'], ['LATIFF,WAZIR', 'VREEKEN,CONNOR', 'SHEPHARD,GRANT', 'KNIGHT,JACOB', 'KNIGHT,JACOB'], ['LATIFF,WAZIR', 'VREEKEN,CONNOR', 'SHEPHARD,GRANT', 'KNIGHT,JACOB', 'KNIGHT,JACOB'], ['VREEKEN,CONNOR', 'SHEPHARD,GRANT', 'KNIGHT,JACOB', 'KNIGHT,JACOB', 'WARNHOLTZ,AIDEN'], ['VREEKEN,CONNOR', 'SHEPHARD,GRANT', 'KNIGHT,JACOB', 'KNIGHT,JACOB', 'WARNHOLTZ,AIDEN'], ['VREEKEN,CONNOR', 'KNIGHT,JACOB', 'KNIGHT,JACOB', 'WARNHOLTZ,AIDEN', 'WARNHOLTZ,AIDEN'], ['KNIGHT,JACOB', 'KNIGHT,JACOB', 'WARNHOLTZ,AIDEN', 'WARNHOLTZ,AIDEN', 'DOLMAN,LUKA'], ['KNIGHT,JACOB', 'WARNHOLTZ,AIDEN', 'WARNHOLTZ,AIDEN', 'DOLMAN,LUKA', 'DOLMAN,LUKA'], ['WARNHOLTZ,AIDEN', 'WARNHOLTZ,AIDEN', 'DOLMAN,LUKA', 'DOLMAN,LUKA', 'BAILEY,ELLIOT'], ['WARNHOLTZ,AIDEN', 'DOLMAN,LUKA', 'DOLMAN,LUKA', 'BAILEY,ELLIOT', 'RILEY,BEN'], ['DOLMAN,LUKA', 'DOLMAN,LUKA', 'BAILEY,ELLIOT', 'RILEY,BEN', 'MEYER,EVAN'], ['DOLMAN,LUKA', 'BAILEY,ELLIOT', 'RILEY,BEN', 'MEYER,EVAN', 'OKADO,MARJOK'], ['DOLMAN,LUKA', 'BAILEY,ELLIOT', 'RILEY,BEN', 'MEYER,EVAN', 'OKADO,MARJOK'], ['BAILEY,ELLIOT', 'RILEY,BEN', 'MEYER,EVAN', 'OKADO,MARJOK', 'OKADO,MARJOK'], ['BAILEY,ELLIOT', 'RILEY,BEN', 'MEYER,EVAN', 'OKADO,MARJOK', 'OKADO,MARJOK']]

In [ ]:
lineup = pd.DataFrame(lineup_history)

In [ ]:
lineup

,0,1,2,3,4
0,"WARNHOLTZ,AIDEN","SERAPH,REGINALD JEAN","LATIFF,WAZIR","SHEPHARD,GRANT","RILEY,BEN"
1,"WARNHOLTZ,AIDEN","LATIFF,WAZIR","SHEPHARD,GRANT","RILEY,BEN","RILEY,BEN"
2,"WARNHOLTZ,AIDEN","LATIFF,WAZIR","RILEY,BEN","RILEY,BEN","RILEY,BEN"
3,"LATIFF,WAZIR","RILEY,BEN","RILEY,BEN","RILEY,BEN","OKADO,MARJOK"
4,"RILEY,BEN","RILEY,BEN","RILEY,BEN","OKADO,MARJOK","OKADO,MARJOK"
5,"RILEY,BEN","RILEY,BEN","OKADO,MARJOK","OKADO,MARJOK","MEYER,EVAN"
6,"RILEY,BEN","OKADO,MARJOK","OKADO,MARJOK","MEYER,EVAN","SERAPH,REGINALD JEAN"
7,"OKADO,MARJOK","OKADO,MARJOK","MEYER,EVAN","SERAPH,REGINALD JEAN","LATIFF,WAZIR"
8,"OKADO,MARJOK","MEYER,EVAN","SERAPH,REGINALD JEAN","LATIFF,WAZIR","BAILEY,ELLIOT"
9,"OKADO,MARJOK","MEYER,EVAN","SERAPH,REGINALD JEAN","LATIFF,WAZIR","BAILEY,ELLIOT"
10,"OKADO,MARJOK","MEYER,EVAN","SERAPH,REGINALD JEAN","LATIFF,WAZIR","BAILEY,ELLIOT"
11,"OKADO,MARJOK","MEYER,EVAN","SERAPH,REGINALD JEAN","LATIFF,WAZIR","BAILEY,ELLIOT"
12,"MEYER,EVAN","SERAPH,REGINALD JEAN","LATIFF,WAZIR","BAILEY,ELLIOT","VREEKEN,CONNOR"
13,"SERAPH,REGINALD JEAN","LATIFF,WAZIR","BAILEY,ELLIOT","VREEKEN,CONNOR","SHEPHARD,GRANT"
14,"LATIFF,WAZIR","BAILEY,ELLIOT","VREEKEN,CONNOR","SHEPHARD,GRANT","KNIGHT,JACOB"
15,"LATIFF,WAZIR","VREEKEN,CONNOR","SHEPHARD,GRANT","KNIGHT,JACOB","KNIGHT,JACOB"
16,"LATIFF,WAZIR","VREEKEN,CONNOR","SHEPHARD,GRANT","KNIGHT,JACOB","KNIGHT,JACOB"
17,"LATIFF,WAZIR","VREEKEN,CONNOR","SHEPHARD,GRANT","KNIGHT,JACOB","KNIGHT,JACOB"
18,"VREEKEN,CONNOR","SHEPHARD,GRANT","KNIGHT,JACOB","KNIGHT,JACOB","WARNHOLTZ,AIDEN"
19,"VREEKEN,CONNOR","SHEPHARD,GRANT","KNIGHT,JACOB","KNIGHT,JACOB","WARNHOLTZ,AIDEN"
20,"VREEKEN,CONNOR","KNIGHT,JACOB","KNIGHT,JACOB","WARNHOLTZ,AIDEN","WARNHOLTZ,AIDEN"
21,"KNIGHT,JACOB","KNIGHT,JACOB","WARNHOLTZ,AIDEN","WARNHOLTZ,AIDEN","DOLMAN,LUKA"
22,"KNIGHT,JACOB","WARNHOLTZ,AIDEN","WARNHOLTZ,AIDEN","DOLMAN,LUKA","DOLMAN,LUKA"
23,"WARNHOLTZ,AIDEN","WARNHOLTZ,AIDEN","DOLMAN,LUKA","DOLMAN,LUKA","BAILEY,ELLIOT"
24,"WARNHOLTZ,AIDEN","DOLMAN,LUKA","DOLMAN,LUKA","BAILEY,ELLIOT","RILEY,BEN"
25,"DOLMAN,LUKA","DOLMAN,LUKA","BAILEY,ELLIOT","RILEY,BEN","MEYER,EVAN"
26,"DOLMAN,LUKA","BAILEY,ELLIOT","RILEY,BEN","MEYER,EVAN","OKADO,MARJOK"
27,"DOLMAN,LUKA","BAILEY,ELLIOT","RILEY,BEN","MEYER,EVAN","OKADO,MARJOK"
28,"BAILEY,ELLIOT","RILEY,BEN","MEYER,EVAN","OKADO,MARJOK","OKADO,MARJOK"
29,"BAILEY,ELLIOT","RILEY,BEN","MEYER,EVAN","OKADO,MARJOK","OKADO,MARJOK"

ZeroDivisionError: float division by zero

In [ ]:
import pandas as pd

# Sample DataFrame
# (Your data here)

# Starting lineup
# Starting lineup
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = starting_lineup.copy()
    lineup_history = []
    lineup_start_time = 0
    lineup_stats = {'points_scored': 0, 'points_conceded': 0, 'minutes': 0, 'net_rating': 0}

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
                lineup_start_time = row['Minutes'] * 60 + row['seconds']
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) < 5:
                    player_in = current_lineup[-1]
                    current_lineup.append(player_in)
                    player_substitutions.append((player, player_in))
                lineup_end_time = row['Minutes'] * 60 + row['seconds']
                lineup_stats['minutes'] += lineup_end_time - lineup_start_time
                lineup_stats['points_scored'] += row['Visitor score']
                lineup_stats['points_conceded'] += row['Home score']

        lineup_history.append((current_lineup.copy(), lineup_stats.copy()))

    return player_substitutions, lineup_history

def calculate_net_rating(points_scored, points_conceded, minutes):
    return (points_scored - points_conceded) / (minutes / 60) if minutes > 0 else 0

player_substitutions, lineup_history = track_player_substitutions(df, starter)

# Create a DataFrame for player substitutions
player_substitutions_df = pd.DataFrame(player_substitutions, columns=['Player Out', 'Player In'])

# Create a DataFrame for lineup history with stats
lineup_history_df = pd.DataFrame(lineup_history, columns=['Lineup', 'Stats'])

# Calculate net rating for each lineup in the DataFrame
lineup_history_df['Net Rating'] = lineup_history_df['Stats'].apply(lambda x: calculate_net_rating(x['points_scored'], x['points_conceded'], x['minutes']))

# Print player substitutions and lineup stats
print("Player Substitutions:")
print(player_substitutions_df)

print("\nLineup History with Stats:")
print(lineup_history_df)

Player Substitutions:
              Player Out             Player In
0         VREEKEN,CONNOR             RILEY,BEN
1   SERAPH,REGINALD JEAN             RILEY,BEN
2         SHEPHARD,GRANT             RILEY,BEN
3        WARNHOLTZ,AIDEN          OKADO,MARJOK
4           LATIFF,WAZIR          OKADO,MARJOK
5              RILEY,BEN            MEYER,EVAN
6              RILEY,BEN  SERAPH,REGINALD JEAN
7              RILEY,BEN          LATIFF,WAZIR
8           OKADO,MARJOK         BAILEY,ELLIOT
9           OKADO,MARJOK        VREEKEN,CONNOR
10            MEYER,EVAN        SHEPHARD,GRANT
11  SERAPH,REGINALD JEAN          KNIGHT,JACOB
12         BAILEY,ELLIOT          KNIGHT,JACOB
13          LATIFF,WAZIR       WARNHOLTZ,AIDEN
14        SHEPHARD,GRANT       WARNHOLTZ,AIDEN
15        VREEKEN,CONNOR           DOLMAN,LUKA
16          KNIGHT,JACOB           DOLMAN,LUKA
17          KNIGHT,JACOB         BAILEY,ELLIOT
18       WARNHOLTZ,AIDEN             RILEY,BEN
19       WARNHOLTZ,AIDEN            MEYER,EVAN
20           DOLMAN,LUKA          OKADO,MARJOK
21           DOLMAN,LUKA          OKADO,MARJOK

Lineup History with Stats:
                                               Lineup  \
0   [WARNHOLTZ,AIDEN, SERAPH,REGINALD JEAN, LATIFF...
1   [WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...
2   [WARNHOLTZ,AIDEN, LATIFF,WAZIR, RILEY,BEN, RIL...
3   [LATIFF,WAZIR, RILEY,BEN, RILEY,BEN, RILEY,BEN...
4   [RILEY,BEN, RILEY,BEN, RILEY,BEN, OKADO,MARJOK...
5   [RILEY,BEN, RILEY,BEN, OKADO,MARJOK, OKADO,MAR...
6   [RILEY,BEN, OKADO,MARJOK, OKADO,MARJOK, MEYER,...
7   [OKADO,MARJOK, OKADO,MARJOK, MEYER,EVAN, SERAP...
8   [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...
9   [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...
10  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...
11  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...
12  [MEYER,EVAN, SERAPH,REGINALD JEAN, LATIFF,WAZI...
13  [SERAPH,REGINALD JEAN, LATIFF,WAZIR, BAILEY,EL...
14  [LATIFF,WAZIR, BAILEY,ELLIOT, VREEKEN,CONNOR, ...
15  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...
16  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...
17  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...
18  [VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...
19  [VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...
20  [VREEKEN,CONNOR, KNIGHT,JACOB, KNIGHT,JACOB, W...
21  [KNIGHT,JACOB, KNIGHT,JACOB, WARNHOLTZ,AIDEN, ...
22  [KNIGHT,JACOB, WARNHOLTZ,AIDEN, WARNHOLTZ,AIDE...
23  [WARNHOLTZ,AIDEN, WARNHOLTZ,AIDEN, DOLMAN,LUKA...
24  [WARNHOLTZ,AIDEN, DOLMAN,LUKA, DOLMAN,LUKA, BA...
25  [DOLMAN,LUKA, DOLMAN,LUKA, BAILEY,ELLIOT, RILE...
26  [DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...
27  [DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...
28  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...
29  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...

                                                Stats  Net Rating
0   {'points_scored': 0, 'points_conceded': 0, 'mi...           0
1   {'points_scored': 4, 'points_conceded': 0, 'mi...           0
2   {'points_scored': 8, 'points_conceded': 0, 'mi...           0
3   {'points_scored': 8, 'points_conceded': 0, 'mi...           0
4   {'points_scored': 12, 'points_conceded': 2, 'm...           0
5   {'points_scored': 12, 'points_conceded': 2, 'm...           0
6   {'points_scored': 12, 'points_conceded': 2, 'm...           0
7   {'points_scored': 12, 'points_conceded': 2, 'm...           0
8   {'points_scored': 12, 'points_conceded': 2, 'm...           0
9   {'points_scored': 12, 'points_conceded': 2, 'm...           0
10  {'points_scored': 12, 'points_conceded': 2, 'm...           0
11  {'points_scored': 12, 'points_conceded': 2, 'm...           0
12  {'points_scored': 12, 'points_conceded': 2, 'm...           0
13  {'points_scored': 12, 'points_conceded': 2, 'm...           0
14  {'points_scored': 12, 'points_conceded': 2, 'm...           0
15  {'points_scored': 28, 'points_conceded': 7, 'm...           0
16  {'points_scored': 28, 'points_conceded': 7, 'm...           0
17  {'points_scored': 28, 'points_conceded': 7, 'm...           0
18  {'points_scored': 28, 'points_conceded': 7, 'm...           0
19  {'points_scored': 28, 'points_conceded': 7, 'm...           0
20  {'points_scored': 48, 'points_conceded': 13, '...           0
21  {'points_scored': 48, 'points_conceded': 13, '...           0
22  {'points_scored': 71, 'points_conceded': 19, '...           0
23  {'points_scored': 71, 'points_conceded': 19, '...           0
24  {'points_scored': 71, 'points_conceded': 19, '...           0
25  {'points_scored': 71, 'points_conceded': 19, '...           0
26  {'points_scored': 71, 'points_conceded': 19, '...           0
27  {'points_scored': 71, 'points_conceded': 19, '...           0
28  {'points_scored': 96, 'points_conceded': 27, '...           0
29  {'points_scored': 96, 'points_conceded': 27, '...           0

In [ ]:
lineup_history_df

,Lineup,Stats,Net Rating
0,"[WARNHOLTZ,AIDEN, SERAPH,REGINALD JEAN, LATIFF...","{'points_scored': 0, 'points_conceded': 0, 'mi...",0
1,"[WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...","{'points_scored': 4, 'points_conceded': 0, 'mi...",0
2,"[WARNHOLTZ,AIDEN, LATIFF,WAZIR, RILEY,BEN, RIL...","{'points_scored': 8, 'points_conceded': 0, 'mi...",0
3,"[LATIFF,WAZIR, RILEY,BEN, RILEY,BEN, RILEY,BEN...","{'points_scored': 8, 'points_conceded': 0, 'mi...",0
4,"[RILEY,BEN, RILEY,BEN, RILEY,BEN, OKADO,MARJOK...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
5,"[RILEY,BEN, RILEY,BEN, OKADO,MARJOK, OKADO,MAR...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
6,"[RILEY,BEN, OKADO,MARJOK, OKADO,MARJOK, MEYER,...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
7,"[OKADO,MARJOK, OKADO,MARJOK, MEYER,EVAN, SERAP...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
8,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
9,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
10,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
11,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
12,"[MEYER,EVAN, SERAPH,REGINALD JEAN, LATIFF,WAZI...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
13,"[SERAPH,REGINALD JEAN, LATIFF,WAZIR, BAILEY,EL...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
14,"[LATIFF,WAZIR, BAILEY,ELLIOT, VREEKEN,CONNOR, ...","{'points_scored': 12, 'points_conceded': 2, 'm...",0
15,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...","{'points_scored': 28, 'points_conceded': 7, 'm...",0
16,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...","{'points_scored': 28, 'points_conceded': 7, 'm...",0
17,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...","{'points_scored': 28, 'points_conceded': 7, 'm...",0
18,"[VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...","{'points_scored': 28, 'points_conceded': 7, 'm...",0
19,"[VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...","{'points_scored': 28, 'points_conceded': 7, 'm...",0
20,"[VREEKEN,CONNOR, KNIGHT,JACOB, KNIGHT,JACOB, W...","{'points_scored': 48, 'points_conceded': 13, '...",0
21,"[KNIGHT,JACOB, KNIGHT,JACOB, WARNHOLTZ,AIDEN, ...","{'points_scored': 48, 'points_conceded': 13, '...",0
22,"[KNIGHT,JACOB, WARNHOLTZ,AIDEN, WARNHOLTZ,AIDE...","{'points_scored': 71, 'points_conceded': 19, '...",0
23,"[WARNHOLTZ,AIDEN, WARNHOLTZ,AIDEN, DOLMAN,LUKA...","{'points_scored': 71, 'points_conceded': 19, '...",0
24,"[WARNHOLTZ,AIDEN, DOLMAN,LUKA, DOLMAN,LUKA, BA...","{'points_scored': 71, 'points_conceded': 19, '...",0
25,"[DOLMAN,LUKA, DOLMAN,LUKA, BAILEY,ELLIOT, RILE...","{'points_scored': 71, 'points_conceded': 19, '...",0
26,"[DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...","{'points_scored': 71, 'points_conceded': 19, '...",0
27,"[DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...","{'points_scored': 71, 'points_conceded': 19, '...",0
28,"[BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...","{'points_scored': 96, 'points_conceded': 27, '...",0
29,"[BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...","{'points_scored': 96, 'points_conceded': 27, '...",0

In [ ]:
# Starting lineup
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = starting_lineup.copy()
    lineup_history = []
    lineup_start_time = 0
    lineup_stats = {'points_scored': 0, 'points_conceded': 0, 'minutes': 0, 'net_rating': 0}

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
                lineup_start_time = row['Minutes'] * 60 + row['seconds']
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) < 5:
                    player_in = current_lineup[-1]
                    current_lineup.append(player_in)
                    player_substitutions.append((player, player_in))
                lineup_end_time = row['Minutes'] * 60 + row['seconds']
                lineup_stats['minutes'] += lineup_end_time - lineup_start_time
                lineup_stats['points_scored'] += row['Visitor score']
                lineup_stats['points_conceded'] += row['Home score']

        lineup_history.append((current_lineup.copy(), lineup_stats.copy()))

    return player_substitutions, lineup_history

def calculate_net_rating(points_scored, points_conceded, minutes):
    return (points_scored - points_conceded) / (minutes / 60) if minutes > 0 else 0

player_substitutions, lineup_history = track_player_substitutions(df, starter)

# Create a DataFrame for player substitutions
player_substitutions_df = pd.DataFrame(player_substitutions, columns=['Player Out', 'Player In'])

# Create a DataFrame for lineup history with stats
lineup_history_df = pd.DataFrame(lineup_history, columns=['Lineup', 'Stats'])

# Split the 'Stats' column into separate columns
lineup_history_df[['Points Scored', 'Points Conceded', 'Minutes', 'Net Rating']] = pd.DataFrame(lineup_history_df['Stats'].tolist(), index=lineup_history_df.index)

# Drop the original 'Stats' column
lineup_history_df.drop(columns=['Stats'], inplace=True)

# Print player substitutions and lineup stats
print("Player Substitutions:")
print(player_substitutions_df)

print("\nLineup History with Stats:")
print(lineup_history_df)

Player Substitutions:
              Player Out             Player In
0         VREEKEN,CONNOR             RILEY,BEN
1   SERAPH,REGINALD JEAN             RILEY,BEN
2         SHEPHARD,GRANT             RILEY,BEN
3        WARNHOLTZ,AIDEN          OKADO,MARJOK
4           LATIFF,WAZIR          OKADO,MARJOK
5              RILEY,BEN            MEYER,EVAN
6              RILEY,BEN  SERAPH,REGINALD JEAN
7              RILEY,BEN          LATIFF,WAZIR
8           OKADO,MARJOK         BAILEY,ELLIOT
9           OKADO,MARJOK        VREEKEN,CONNOR
10            MEYER,EVAN        SHEPHARD,GRANT
11  SERAPH,REGINALD JEAN          KNIGHT,JACOB
12         BAILEY,ELLIOT          KNIGHT,JACOB
13          LATIFF,WAZIR       WARNHOLTZ,AIDEN
14        SHEPHARD,GRANT       WARNHOLTZ,AIDEN
15        VREEKEN,CONNOR           DOLMAN,LUKA
16          KNIGHT,JACOB           DOLMAN,LUKA
17          KNIGHT,JACOB         BAILEY,ELLIOT
18       WARNHOLTZ,AIDEN             RILEY,BEN
19       WARNHOLTZ,AIDEN            MEYER,EVAN
20           DOLMAN,LUKA          OKADO,MARJOK
21           DOLMAN,LUKA          OKADO,MARJOK

Lineup History with Stats:
                                               Lineup  Points Scored  \
0   [WARNHOLTZ,AIDEN, SERAPH,REGINALD JEAN, LATIFF...              0
1   [WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...              4
2   [WARNHOLTZ,AIDEN, LATIFF,WAZIR, RILEY,BEN, RIL...              8
3   [LATIFF,WAZIR, RILEY,BEN, RILEY,BEN, RILEY,BEN...              8
4   [RILEY,BEN, RILEY,BEN, RILEY,BEN, OKADO,MARJOK...             12
5   [RILEY,BEN, RILEY,BEN, OKADO,MARJOK, OKADO,MAR...             12
6   [RILEY,BEN, OKADO,MARJOK, OKADO,MARJOK, MEYER,...             12
7   [OKADO,MARJOK, OKADO,MARJOK, MEYER,EVAN, SERAP...             12
8   [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...             12
9   [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...             12
10  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...             12
11  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...             12
12  [MEYER,EVAN, SERAPH,REGINALD JEAN, LATIFF,WAZI...             12
13  [SERAPH,REGINALD JEAN, LATIFF,WAZIR, BAILEY,EL...             12
14  [LATIFF,WAZIR, BAILEY,ELLIOT, VREEKEN,CONNOR, ...             12
15  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...             28
16  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...             28
17  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...             28
18  [VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...             28
19  [VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...             28
20  [VREEKEN,CONNOR, KNIGHT,JACOB, KNIGHT,JACOB, W...             48
21  [KNIGHT,JACOB, KNIGHT,JACOB, WARNHOLTZ,AIDEN, ...             48
22  [KNIGHT,JACOB, WARNHOLTZ,AIDEN, WARNHOLTZ,AIDE...             71
23  [WARNHOLTZ,AIDEN, WARNHOLTZ,AIDEN, DOLMAN,LUKA...             71
24  [WARNHOLTZ,AIDEN, DOLMAN,LUKA, DOLMAN,LUKA, BA...             71
25  [DOLMAN,LUKA, DOLMAN,LUKA, BAILEY,ELLIOT, RILE...             71
26  [DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...             71
27  [DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...             71
28  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...             96
29  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...             96

    Points Conceded  Minutes  Net Rating
0                 0        0           0
1                 0        0           0
2                 0        0           0
3                 0        0           0
4                 2        0           0
5                 2        0           0
6                 2        0           0
7                 2        0           0
8                 2        0           0
9                 2        0           0
10                2        0           0
11                2        0           0
12                2        0           0
13                2        0           0
14                2        0           0
15                7        0           0
16                7        0           0
17                7        0           0
18                7        0           0
19                7        0           0
20               13        0           0
21               13        0           0
22               19        0           0
23               19        0           0
24               19        0           0
25               19        0           0
26               19        0           0
27               19        0           0
28               27        0           0
29               27        0           0

In [ ]:
lineup_history_df

,Lineup,Points Scored,Points Conceded,Minutes,Net Rating
0,"[WARNHOLTZ,AIDEN, SERAPH,REGINALD JEAN, LATIFF...",0,0,0,0
1,"[WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...",4,0,0,0
2,"[WARNHOLTZ,AIDEN, LATIFF,WAZIR, RILEY,BEN, RIL...",8,0,0,0
3,"[LATIFF,WAZIR, RILEY,BEN, RILEY,BEN, RILEY,BEN...",8,0,0,0
4,"[RILEY,BEN, RILEY,BEN, RILEY,BEN, OKADO,MARJOK...",12,2,0,0
5,"[RILEY,BEN, RILEY,BEN, OKADO,MARJOK, OKADO,MAR...",12,2,0,0
6,"[RILEY,BEN, OKADO,MARJOK, OKADO,MARJOK, MEYER,...",12,2,0,0
7,"[OKADO,MARJOK, OKADO,MARJOK, MEYER,EVAN, SERAP...",12,2,0,0
8,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",12,2,0,0
9,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",12,2,0,0
10,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",12,2,0,0
11,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",12,2,0,0
12,"[MEYER,EVAN, SERAPH,REGINALD JEAN, LATIFF,WAZI...",12,2,0,0
13,"[SERAPH,REGINALD JEAN, LATIFF,WAZIR, BAILEY,EL...",12,2,0,0
14,"[LATIFF,WAZIR, BAILEY,ELLIOT, VREEKEN,CONNOR, ...",12,2,0,0
15,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...",28,7,0,0
16,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...",28,7,0,0
17,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...",28,7,0,0
18,"[VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...",28,7,0,0
19,"[VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...",28,7,0,0
20,"[VREEKEN,CONNOR, KNIGHT,JACOB, KNIGHT,JACOB, W...",48,13,0,0
21,"[KNIGHT,JACOB, KNIGHT,JACOB, WARNHOLTZ,AIDEN, ...",48,13,0,0
22,"[KNIGHT,JACOB, WARNHOLTZ,AIDEN, WARNHOLTZ,AIDE...",71,19,0,0
23,"[WARNHOLTZ,AIDEN, WARNHOLTZ,AIDEN, DOLMAN,LUKA...",71,19,0,0
24,"[WARNHOLTZ,AIDEN, DOLMAN,LUKA, DOLMAN,LUKA, BA...",71,19,0,0
25,"[DOLMAN,LUKA, DOLMAN,LUKA, BAILEY,ELLIOT, RILE...",71,19,0,0
26,"[DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...",71,19,0,0
27,"[DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...",71,19,0,0
28,"[BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...",96,27,0,0
29,"[BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...",96,27,0,0

In [ ]:
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = starting_lineup.copy()
    lineup_history = []
    lineup_start_time = 0
    lineup_stats = {'points_scored': 0, 'points_conceded': 0, 'minutes': 0, 'net_rating': 0}

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
                lineup_start_time = row['Minutes'] * 60 + row['seconds']
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) < 5:
                    player_in = current_lineup[-1]
                    current_lineup.append(player_in)
                    player_substitutions.append((player, player_in))
                lineup_end_time = row['Minutes'] * 60 + row['seconds']
                lineup_stats['minutes'] += lineup_end_time - lineup_start_time
                lineup_stats['points_scored'] += row['Visitor score']
                lineup_stats['points_conceded'] += row['Home score']

        lineup_history.append((current_lineup.copy(), lineup_stats.copy()))

    return player_substitutions, lineup_history

def calculate_net_rating(points_scored, points_conceded, minutes):
    return (points_scored - points_conceded) / (minutes / 60) if minutes > 0 else 0

player_substitutions, lineup_history = track_player_substitutions(df, starter)

# Create a DataFrame for player substitutions
player_substitutions_df = pd.DataFrame(player_substitutions, columns=['Player Out', 'Player In'])

# Create a DataFrame for lineup history with stats
lineup_history_df = pd.DataFrame(lineup_history, columns=['Lineup', 'Stats'])

# Split the 'Stats' column into separate columns
lineup_history_df[['Points Scored', 'Points Conceded', 'Minutes', 'Net Rating']] = pd.DataFrame(lineup_history_df['Stats'].tolist(), index=lineup_history_df.index)

# Drop the original 'Stats' column
lineup_history_df.drop(columns=['Stats'], inplace=True)

# Print player substitutions and lineup stats
print("Player Substitutions:")
print(player_substitutions_df)

print("\nLineup History with Stats:")
print(lineup_history_df)

Player Substitutions:
              Player Out             Player In
0         VREEKEN,CONNOR             RILEY,BEN
1   SERAPH,REGINALD JEAN             RILEY,BEN
2         SHEPHARD,GRANT             RILEY,BEN
3        WARNHOLTZ,AIDEN          OKADO,MARJOK
4           LATIFF,WAZIR          OKADO,MARJOK
5              RILEY,BEN            MEYER,EVAN
6              RILEY,BEN  SERAPH,REGINALD JEAN
7              RILEY,BEN          LATIFF,WAZIR
8           OKADO,MARJOK         BAILEY,ELLIOT
9           OKADO,MARJOK        VREEKEN,CONNOR
10            MEYER,EVAN        SHEPHARD,GRANT
11  SERAPH,REGINALD JEAN          KNIGHT,JACOB
12         BAILEY,ELLIOT          KNIGHT,JACOB
13          LATIFF,WAZIR       WARNHOLTZ,AIDEN
14        SHEPHARD,GRANT       WARNHOLTZ,AIDEN
15        VREEKEN,CONNOR           DOLMAN,LUKA
16          KNIGHT,JACOB           DOLMAN,LUKA
17          KNIGHT,JACOB         BAILEY,ELLIOT
18       WARNHOLTZ,AIDEN             RILEY,BEN
19       WARNHOLTZ,AIDEN            MEYER,EVAN
20           DOLMAN,LUKA          OKADO,MARJOK
21           DOLMAN,LUKA          OKADO,MARJOK

Lineup History with Stats:
                                               Lineup  Points Scored  \
0   [WARNHOLTZ,AIDEN, SERAPH,REGINALD JEAN, LATIFF...              0
1   [WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...              4
2   [WARNHOLTZ,AIDEN, LATIFF,WAZIR, RILEY,BEN, RIL...              8
3   [LATIFF,WAZIR, RILEY,BEN, RILEY,BEN, RILEY,BEN...              8
4   [RILEY,BEN, RILEY,BEN, RILEY,BEN, OKADO,MARJOK...             12
5   [RILEY,BEN, RILEY,BEN, OKADO,MARJOK, OKADO,MAR...             12
6   [RILEY,BEN, OKADO,MARJOK, OKADO,MARJOK, MEYER,...             12
7   [OKADO,MARJOK, OKADO,MARJOK, MEYER,EVAN, SERAP...             12
8   [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...             12
9   [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...             12
10  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...             12
11  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...             12
12  [MEYER,EVAN, SERAPH,REGINALD JEAN, LATIFF,WAZI...             12
13  [SERAPH,REGINALD JEAN, LATIFF,WAZIR, BAILEY,EL...             12
14  [LATIFF,WAZIR, BAILEY,ELLIOT, VREEKEN,CONNOR, ...             12
15  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...             28
16  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...             28
17  [LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...             28
18  [VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...             28
19  [VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...             28
20  [VREEKEN,CONNOR, KNIGHT,JACOB, KNIGHT,JACOB, W...             48
21  [KNIGHT,JACOB, KNIGHT,JACOB, WARNHOLTZ,AIDEN, ...             48
22  [KNIGHT,JACOB, WARNHOLTZ,AIDEN, WARNHOLTZ,AIDE...             71
23  [WARNHOLTZ,AIDEN, WARNHOLTZ,AIDEN, DOLMAN,LUKA...             71
24  [WARNHOLTZ,AIDEN, DOLMAN,LUKA, DOLMAN,LUKA, BA...             71
25  [DOLMAN,LUKA, DOLMAN,LUKA, BAILEY,ELLIOT, RILE...             71
26  [DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...             71
27  [DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...             71
28  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...             96
29  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...             96

    Points Conceded  Minutes  Net Rating
0                 0        0           0
1                 0        0           0
2                 0        0           0
3                 0        0           0
4                 2        0           0
5                 2        0           0
6                 2        0           0
7                 2        0           0
8                 2        0           0
9                 2        0           0
10                2        0           0
11                2        0           0
12                2        0           0
13                2        0           0
14                2        0           0
15                7        0           0
16                7        0           0
17                7        0           0
18                7        0           0
19                7        0           0
20               13        0           0
21               13        0           0
22               19        0           0
23               19        0           0
24               19        0           0
25               19        0           0
26               19        0           0
27               19        0           0
28               27        0           0
29               27        0           0

In [ ]:
lineup_history_df

,Lineup,Points Scored,Points Conceded,Minutes,Net Rating
0,"[WARNHOLTZ,AIDEN, SERAPH,REGINALD JEAN, LATIFF...",0,0,0,0
1,"[WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...",4,0,0,0
2,"[WARNHOLTZ,AIDEN, LATIFF,WAZIR, RILEY,BEN, RIL...",8,0,0,0
3,"[LATIFF,WAZIR, RILEY,BEN, RILEY,BEN, RILEY,BEN...",8,0,0,0
4,"[RILEY,BEN, RILEY,BEN, RILEY,BEN, OKADO,MARJOK...",12,2,0,0
5,"[RILEY,BEN, RILEY,BEN, OKADO,MARJOK, OKADO,MAR...",12,2,0,0
6,"[RILEY,BEN, OKADO,MARJOK, OKADO,MARJOK, MEYER,...",12,2,0,0
7,"[OKADO,MARJOK, OKADO,MARJOK, MEYER,EVAN, SERAP...",12,2,0,0
8,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",12,2,0,0
9,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",12,2,0,0
10,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",12,2,0,0
11,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",12,2,0,0
12,"[MEYER,EVAN, SERAPH,REGINALD JEAN, LATIFF,WAZI...",12,2,0,0
13,"[SERAPH,REGINALD JEAN, LATIFF,WAZIR, BAILEY,EL...",12,2,0,0
14,"[LATIFF,WAZIR, BAILEY,ELLIOT, VREEKEN,CONNOR, ...",12,2,0,0
15,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...",28,7,0,0
16,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...",28,7,0,0
17,"[LATIFF,WAZIR, VREEKEN,CONNOR, SHEPHARD,GRANT,...",28,7,0,0
18,"[VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...",28,7,0,0
19,"[VREEKEN,CONNOR, SHEPHARD,GRANT, KNIGHT,JACOB,...",28,7,0,0
20,"[VREEKEN,CONNOR, KNIGHT,JACOB, KNIGHT,JACOB, W...",48,13,0,0
21,"[KNIGHT,JACOB, KNIGHT,JACOB, WARNHOLTZ,AIDEN, ...",48,13,0,0
22,"[KNIGHT,JACOB, WARNHOLTZ,AIDEN, WARNHOLTZ,AIDE...",71,19,0,0
23,"[WARNHOLTZ,AIDEN, WARNHOLTZ,AIDEN, DOLMAN,LUKA...",71,19,0,0
24,"[WARNHOLTZ,AIDEN, DOLMAN,LUKA, DOLMAN,LUKA, BA...",71,19,0,0
25,"[DOLMAN,LUKA, DOLMAN,LUKA, BAILEY,ELLIOT, RILE...",71,19,0,0
26,"[DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...",71,19,0,0
27,"[DOLMAN,LUKA, BAILEY,ELLIOT, RILEY,BEN, MEYER,...",71,19,0,0
28,"[BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...",96,27,0,0
29,"[BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...",96,27,0,0

In [ ]:
import pandas as pd

# Sample DataFrame
# (Your data here)

# Starting lineup
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = list(starting_lineup)
    lineup_history = []
    current_lineup_stats = {'points_scored': 0, 'points_conceded': 0, 'minutes': 0, 'net_rating': 0}

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup[0]
                current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
                lineup_start_time = row['Minutes'] * 60 + row['seconds']
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) >= 4:
                    current_lineup.append(current_lineup[-1])
                player_substitutions.append((player, current_lineup[-1]))
                lineup_end_time = row['Minutes'] * 60 + row['seconds']
                current_lineup_stats['minutes'] += lineup_end_time - lineup_start_time
                current_lineup_stats['points_scored'] += row['Visitor score']
                current_lineup_stats['points_conceded'] += row['Home score']
                lineup_history.append((list(current_lineup), current_lineup_stats.copy()))

    return player_substitutions, lineup_history

def calculate_net_rating(points_scored, points_conceded, minutes):
    return (points_scored - points_conceded) / (minutes / 60) if minutes > 0 else 0

player_substitutions, lineup_history = track_player_substitutions(df, starter)

# Create a DataFrame for player substitutions
player_substitutions_df = pd.DataFrame(player_substitutions, columns=['Player Out', 'Player In'])

# Create a DataFrame for lineup history with stats
lineup_history_df = pd.DataFrame(lineup_history, columns=['Lineup', 'Stats'])

# Split the 'Stats' column into separate columns
lineup_history_df[['Points Scored', 'Points Conceded', 'Minutes', 'Net Rating']] = pd.DataFrame(lineup_history_df['Stats'].tolist(), index=lineup_history_df.index)

# Drop the original 'Stats' column
lineup_history_df.drop(columns=['Stats'], inplace=True)

# Calculate points scored for each lineup while they were on the court
lineup_history_df['Points Scored While On Court'] = lineup_history_df.groupby('Lineup')['Points Scored'].diff().fillna(lineup_history_df['Points Scored'])

# Print player substitutions and lineup stats
print("Player Substitutions:")
print(player_substitutions_df)

print("\nLineup History with Stats:")
print(lineup_history_df[['Lineup', 'Minutes', 'Points Scored While On Court', 'Net Rating']])

TypeError: unhashable type: 'list'

In [ ]:
lineup_history_df

,Lineup,Points Scored,Points Conceded,Minutes,Net Rating,Points Scored While On Court
0,"(WARNHOLTZ,AIDEN, SERAPH,REGINALD JEAN, LATIFF...",0,0,0,0,0.0
1,"(WARNHOLTZ,AIDEN, RILEY,BEN)",4,0,0,0,4.0
2,"(WARNHOLTZ,AIDEN, RILEY,BEN)",4,0,0,0,0.0
3,"(WARNHOLTZ,AIDEN, RILEY,BEN)",4,0,0,0,0.0
4,"(WARNHOLTZ,AIDEN, RILEY,BEN)",4,0,0,0,0.0
5,"(WARNHOLTZ,AIDEN, RILEY,BEN)",4,0,0,0,0.0
6,"(WARNHOLTZ,AIDEN, RILEY,BEN)",4,0,0,0,0.0
7,"(RILEY,BEN,)",17,5,-165,0,17.0
8,"(RILEY,BEN,)",30,10,-330,0,13.0
9,"(RILEY,BEN,)",30,10,-330,0,0.0
10,"(RILEY,BEN,)",30,10,-330,0,0.0
11,"(RILEY,BEN,)",30,10,-330,0,0.0
12,"(RILEY,BEN,)",30,10,-330,0,0.0
13,"(RILEY,BEN,)",30,10,-330,0,0.0
14,"(RILEY,BEN,)",30,10,-330,0,0.0
15,"(RILEY,BEN,)",30,10,-330,0,0.0
16,"(RILEY,BEN,)",30,10,-330,0,0.0
17,"(RILEY,BEN,)",30,10,-330,0,0.0
18,"(RILEY,BEN,)",30,10,-330,0,0.0
19,"(RILEY,BEN,)",30,10,-330,0,0.0
20,"(RILEY,BEN,)",30,10,-330,0,0.0
21,"(RILEY,BEN,)",30,10,-330,0,0.0
22,"(RILEY,BEN,)",30,10,-330,0,0.0
23,"(RILEY,BEN,)",30,10,-330,0,0.0

In [ ]:
import pandas as pd

# Sample DataFrame
# (Your data here)

# Starting lineup
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = list(starting_lineup)
    lineup_history = []
    current_lineup_stats = {'points_scored': 0, 'points_conceded': 0, 'minutes': 0, 'net_rating': 0}
    lineup_start_time = None

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup[0]
                current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
                lineup_start_time = row['Minutes'] * 60 + row['seconds']
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) >= 4:
                    current_lineup.append(current_lineup[-1])
                player_substitutions.append((player, current_lineup[-1]))
                lineup_end_time = row['Minutes'] * 60 + row['seconds']
                current_lineup_stats['minutes'] += lineup_end_time - lineup_start_time
                current_lineup_stats['points_scored'] += row['Visitor score']
                current_lineup_stats['points_conceded'] += row['Home score']
                lineup_history.append((list(current_lineup), lineup_start_time, lineup_end_time, current_lineup_stats.copy()))
                lineup_start_time = None

    return player_substitutions, lineup_history

def calculate_net_rating(points_scored, points_conceded, minutes):
    return (points_scored - points_conceded) / (minutes / 60) if minutes > 0 else 0

player_substitutions, lineup_history = track_player_substitutions(df, starter)

# Create a DataFrame for player substitutions
player_substitutions_df = pd.DataFrame(player_substitutions, columns=['Player Out', 'Player In'])

# Create a DataFrame for lineup history with stats
lineup_history_df = pd.DataFrame(lineup_history, columns=['Lineup', 'Start Time', 'End Time', 'Stats'])

# Calculate points scored for each lineup while they were on the court
lineup_history_df['Points Scored While On Court'] = lineup_history_df.apply(
    lambda row: row['Stats']['points_scored'] if row['End Time'] is not None else 0, axis=1
)

# Print player substitutions and lineup stats
print("Player Substitutions:")
print(player_substitutions_df)

print("\nLineup History with Stats:")
print(lineup_history_df[['Lineup', 'Start Time', 'End Time', 'Points Scored While On Court']])

Player Substitutions:
              Player Out             Player In
0         VREEKEN,CONNOR             RILEY,BEN
1   SERAPH,REGINALD JEAN             RILEY,BEN
2        WARNHOLTZ,AIDEN          OKADO,MARJOK
3           LATIFF,WAZIR            MEYER,EVAN
4         SHEPHARD,GRANT  SERAPH,REGINALD JEAN
5              RILEY,BEN         BAILEY,ELLIOT
6              RILEY,BEN         BAILEY,ELLIOT
7           OKADO,MARJOK        VREEKEN,CONNOR
8             MEYER,EVAN          KNIGHT,JACOB
9          BAILEY,ELLIOT          KNIGHT,JACOB
10  SERAPH,REGINALD JEAN       WARNHOLTZ,AIDEN
11         BAILEY,ELLIOT           DOLMAN,LUKA
12          KNIGHT,JACOB           DOLMAN,LUKA
13        VREEKEN,CONNOR         BAILEY,ELLIOT
14          KNIGHT,JACOB             RILEY,BEN
15       WARNHOLTZ,AIDEN            MEYER,EVAN
16           DOLMAN,LUKA          OKADO,MARJOK
17           DOLMAN,LUKA          OKADO,MARJOK

Lineup History with Stats:
                                              Lineup  Start Time  End Time  \
0  [WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...         525       525
1  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...         360       360
2  [SERAPH,REGINALD JEAN, BAILEY,ELLIOT, VREEKEN,...         281       281
3  [VREEKEN,CONNOR, KNIGHT,JACOB, WARNHOLTZ,AIDEN...         128       128
4  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...          39        39

   Points Scored While On Court
0                             4
1                            17
2                            33
3                            56
4                            81

In [ ]:
lineup_history_df

,Lineup,Start Time,End Time,Stats,Points Scored While On Court
0,"[WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...",525,525,"{'points_scored': 4, 'points_conceded': 0, 'mi...",4
1,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",360,360,"{'points_scored': 17, 'points_conceded': 5, 'm...",17
2,"[SERAPH,REGINALD JEAN, BAILEY,ELLIOT, VREEKEN,...",281,281,"{'points_scored': 33, 'points_conceded': 10, '...",33
3,"[VREEKEN,CONNOR, KNIGHT,JACOB, WARNHOLTZ,AIDEN...",128,128,"{'points_scored': 56, 'points_conceded': 16, '...",56
4,"[BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...",39,39,"{'points_scored': 81, 'points_conceded': 24, '...",81

In [ ]:
import pandas as pd

# Sample DataFrame
# (Your data here)

# Starting lineup
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = list(starting_lineup)
    lineup_history = []
    current_lineup_stats = {'points_scored': 0, 'points_conceded': 0, 'minutes': 0, 'net_rating': 0}
    lineup_start_time = None

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup[0]
                current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
                lineup_start_time = row['Minutes'] * 60 + row['seconds']
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) >= 4:
                    current_lineup.append(current_lineup[-1])
                player_substitutions.append((player, current_lineup[-1]))
                lineup_end_time = row['Minutes'] * 60 + row['seconds']
                current_lineup_stats['minutes'] += lineup_end_time - lineup_start_time
                current_lineup_stats['points_scored'] += row['Visitor score']
                current_lineup_stats['points_conceded'] += row['Home score']
                lineup_history.append((list(current_lineup), lineup_start_time, lineup_end_time, current_lineup_stats.copy()))
                lineup_start_time = None

    return player_substitutions, lineup_history

def calculate_net_rating(points_scored, points_conceded, minutes):
    return (points_scored - points_conceded) / (minutes / 60) if minutes > 0 else 0

player_substitutions, lineup_history = track_player_substitutions(df, starter)

# Create a DataFrame for player substitutions
player_substitutions_df = pd.DataFrame(player_substitutions, columns=['Player Out', 'Player In'])

# Create a DataFrame for lineup history with stats
lineup_history_df = pd.DataFrame(lineup_history, columns=['Lineup', 'Start Time', 'End Time', 'Stats'])

# Calculate points scored and points conceded for each lineup while they were on the court together
lineup_history_df['Points Scored'] = lineup_history_df.apply(
    lambda row: row['Stats']['points_scored'], axis=1
)
lineup_history_df['Points Conceded'] = lineup_history_df.apply(
    lambda row: row['Stats']['points_conceded'], axis=1
)

# Print player substitutions and lineup stats
print("Player Substitutions:")
print(player_substitutions_df)

print("\nLineup History with Stats:")
print(lineup_history_df[['Lineup', 'Start Time', 'End Time', 'Points Scored', 'Points Conceded']])

Player Substitutions:
              Player Out             Player In
0         VREEKEN,CONNOR             RILEY,BEN
1   SERAPH,REGINALD JEAN             RILEY,BEN
2        WARNHOLTZ,AIDEN          OKADO,MARJOK
3           LATIFF,WAZIR            MEYER,EVAN
4         SHEPHARD,GRANT  SERAPH,REGINALD JEAN
5              RILEY,BEN         BAILEY,ELLIOT
6              RILEY,BEN         BAILEY,ELLIOT
7           OKADO,MARJOK        VREEKEN,CONNOR
8             MEYER,EVAN          KNIGHT,JACOB
9          BAILEY,ELLIOT          KNIGHT,JACOB
10  SERAPH,REGINALD JEAN       WARNHOLTZ,AIDEN
11         BAILEY,ELLIOT           DOLMAN,LUKA
12          KNIGHT,JACOB           DOLMAN,LUKA
13        VREEKEN,CONNOR         BAILEY,ELLIOT
14          KNIGHT,JACOB             RILEY,BEN
15       WARNHOLTZ,AIDEN            MEYER,EVAN
16           DOLMAN,LUKA          OKADO,MARJOK
17           DOLMAN,LUKA          OKADO,MARJOK

Lineup History with Stats:
                                              Lineup  Start Time  End Time  \
0  [WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...         525       525
1  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...         360       360
2  [SERAPH,REGINALD JEAN, BAILEY,ELLIOT, VREEKEN,...         281       281
3  [VREEKEN,CONNOR, KNIGHT,JACOB, WARNHOLTZ,AIDEN...         128       128
4  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...          39        39

   Points Scored  Points Conceded
0              4                0
1             17                5
2             33               10
3             56               16
4             81               24

In [ ]:
import pandas as pd

# Sample DataFrame
# (Your data here)

# Starting lineup
starter = ['VREEKEN,CONNOR', 'WARNHOLTZ,AIDEN', 'SERAPH,REGINALD JEAN', 'LATIFF,WAZIR', 'SHEPHARD,GRANT']

def track_player_substitutions(data_frame, starting_lineup):
    player_substitutions = []
    current_lineup = list(starting_lineup)
    lineup_history = []

    lineup_start_time = None  # Initialize lineup start time

    for _, row in data_frame.iterrows():
        action = row['First_True_Column']
        player = row['Second_True_Column']

        if action == 'enters the game':
            if len(current_lineup) >= 5:
                player_out = current_lineup[0]
                current_lineup.pop(0)
                current_lineup.append(player)
                player_substitutions.append((player_out, player))
                lineup_start_time = row['Minutes'] * 60 + row['seconds']
        elif action == 'goes to the bench':
            if player in current_lineup:
                current_lineup.remove(player)
                if len(current_lineup) >= 4:
                    current_lineup.append(current_lineup[-1])
                player_substitutions.append((player, current_lineup[-1]))
                lineup_end_time = row['Minutes'] * 60 + row['seconds']
                if lineup_start_time is not None:
                    lineup_history.append((list(current_lineup), lineup_start_time, lineup_end_time))
                lineup_start_time = None

    return player_substitutions, lineup_history

player_substitutions, lineup_history = track_player_substitutions(df, starter)

# Create a DataFrame for player substitutions
player_substitutions_df = pd.DataFrame(player_substitutions, columns=['Player Out', 'Player In'])

# Create a DataFrame for lineup history with time duration
lineup_history_df = pd.DataFrame(lineup_history, columns=['Lineup', 'Start Time', 'End Time'])

# Calculate the time duration for each lineup
lineup_history_df['Time Duration (sec)'] = lineup_history_df['End Time'] - lineup_history_df['Start Time']

# Print player substitutions and lineup time duration
print("Player Substitutions:")
print(player_substitutions_df)

print("\nLineup Time Duration:")
print(lineup_history_df[['Lineup', 'Start Time', 'End Time', 'Time Duration (sec)']])

Player Substitutions:
              Player Out             Player In
0         VREEKEN,CONNOR             RILEY,BEN
1   SERAPH,REGINALD JEAN             RILEY,BEN
2        WARNHOLTZ,AIDEN          OKADO,MARJOK
3           LATIFF,WAZIR            MEYER,EVAN
4         SHEPHARD,GRANT  SERAPH,REGINALD JEAN
5              RILEY,BEN         BAILEY,ELLIOT
6              RILEY,BEN         BAILEY,ELLIOT
7           OKADO,MARJOK        VREEKEN,CONNOR
8             MEYER,EVAN          KNIGHT,JACOB
9          BAILEY,ELLIOT          KNIGHT,JACOB
10  SERAPH,REGINALD JEAN       WARNHOLTZ,AIDEN
11         BAILEY,ELLIOT           DOLMAN,LUKA
12          KNIGHT,JACOB           DOLMAN,LUKA
13        VREEKEN,CONNOR         BAILEY,ELLIOT
14          KNIGHT,JACOB             RILEY,BEN
15       WARNHOLTZ,AIDEN            MEYER,EVAN
16           DOLMAN,LUKA          OKADO,MARJOK
17           DOLMAN,LUKA          OKADO,MARJOK

Lineup Time Duration:
                                              Lineup  Start Time  End Time  \
0  [WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...         525       525
1  [OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...         360       360
2  [SERAPH,REGINALD JEAN, BAILEY,ELLIOT, VREEKEN,...         281       281
3  [VREEKEN,CONNOR, KNIGHT,JACOB, WARNHOLTZ,AIDEN...         128       128
4  [BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...          39        39

   Time Duration (sec)
0                    0
1                    0
2                    0
3                    0
4                    0

In [ ]:
lineup_history_df

,Lineup,Start Time,End Time,Time Duration (sec)
0,"[WARNHOLTZ,AIDEN, LATIFF,WAZIR, SHEPHARD,GRANT...",525,525,0
1,"[OKADO,MARJOK, MEYER,EVAN, SERAPH,REGINALD JEA...",360,360,0
2,"[SERAPH,REGINALD JEAN, BAILEY,ELLIOT, VREEKEN,...",281,281,0
3,"[VREEKEN,CONNOR, KNIGHT,JACOB, WARNHOLTZ,AIDEN...",128,128,0
4,"[BAILEY,ELLIOT, RILEY,BEN, MEYER,EVAN, OKADO,M...",39,39,0